### ISSUE TITLE
Service segfault after update to glib2 2.82.3-1

### ISSUE THREAD

**Issue by WyvernDotRed** [sezanzeb/input-remapper#1013]
edit: Narrowed it down to the glib2 update: https://github.com/sezanzeb/input-remapper/issues/1013#issuecomment-2532973478
The issue occurred after updating my Garuda Linux (Arch Linux based) system.
The service segfaults when authenticating for the GUI or loading a Preset.
`systemctl status input-remapper.service` shows the following on this event:
```txt
Dec 10 21:42:02 flight systemd[1]: input-remapper.service: Main process exited, code=dumped, status=11/SEGV
Dec 10 21:42:02 flight systemd[1]: input-remapper.service: Failed with result 'core-dump'.
```
In this update, the following package versions changed:
```txt
[2024-12-10T20:32:45+0100] [ALPM] upgraded glib2 (2.82.2-1 -> 2.82.3-1)
[2024-12-10T20:32:46+0100] [ALPM] upgraded mesa (1:24.3.1-2 -> 1:24.3.1-3)
[2024-12-10T20:32:46+0100] [ALPM] upgraded json-glib (1.10.0-1 -> 1.10.6-1)
[2024-12-10T20:32:46+0100] [ALPM] upgraded discord (0.0.76-1 -> 0.0.77-1)
[2024-12-10T20:32:47+0100] [ALPM] upgraded firedragon (1:11.20.0_1-1 -> 1:11.21.0_1-1)
[2024-12-10T20:32:47+0100] [ALPM] upgraded garuda-dr460nized (4.4.2-4 -> 4.4.3-4)
[2024-12-10T20:32:47+0100] [ALPM] upgraded libgedit-gfls (1:0.2.0-1 -> 1:0.2.1-1)
[2024-12-10T20:32:47+0100] [ALPM] upgraded libgedit-gtksourceview (299.3.0-1 -> 299.4.0-1)
[2024-12-10T20:32:47+0100] [ALPM] upgraded libgedit-tepl (6.11.0-1 -> 6.12.0-1)
[2024-12-10T20:32:48+0100] [ALPM] upgraded gedit (48.0-1 -> 48.1-1)
[2024-12-10T20:32:48+0100] [ALPM] upgraded js128 (128.5.0-1 -> 128.5.1-1)
[2024-12-10T20:32:48+0100] [ALPM] upgraded lib32-glib2 (2.82.2-1 -> 2.82.3-1)
[2024-12-10T20:32:48+0100] [ALPM] upgraded lib32-mesa (1:24.3.1-2 -> 1:24.3.1-3)
[2024-12-10T20:32:49+0100] [ALPM] upgraded vulkan-intel (1:24.3.1-2 -> 1:24.3.1-3)
[2024-12-10T20:32:49+0100] [ALPM] upgraded lib32-vulkan-intel (1:24.3.1-2 -> 1:24.3.1-3)
[2024-12-10T20:32:49+0100] [ALPM] upgraded vulkan-mesa-layers (1:24.3.1-2 -> 1:24.3.1-3)
[2024-12-10T20:32:49+0100] [ALPM] upgraded lib32-vulkan-mesa-layers (1:24.3.1-2 -> 1:24.3.1-3)
[2024-12-10T20:32:49+0100] [ALPM] upgraded vulkan-radeon (1:24.3.1-2 -> 1:24.3.1-3)
[2024-12-10T20:32:49+0100] [ALPM] upgraded lib32-vulkan-radeon (1:24.3.1-2 -> 1:24.3.1-3)
[2024-12-10T20:32:52+0100] [ALPM] upgraded linux-zen (6.12.3.zen1-1 -> 6.12.4.zen1-1)
[2024-12-10T20:32:58+0100] [ALPM] upgraded linux-zen-headers (6.12.3.zen1-1 -> 6.12.4.zen1-1)
[2024-12-10T20:32:58+0100] [ALPM] upgraded ollama-rocm (0.4.3-1 -> 0.5.1-2)
[2024-12-10T20:32:58+0100] [ALPM] upgraded ttf-opensans (1.101-3 -> 1.101-4)
[2024-12-10T20:32:58+0100] [ALPM] upgraded vulkan-swrast (1:24.3.1-2 -> 1:24.3.1-3)
```
As troubleshooting steps I downgraded from `input-remapper-git-2.0.1.r31.g8a980a76` to `input-remapper-git-2.0.1.r30.g291b982e`, then moved to installing `input-remapper-bin 2.0.1-2` instead, making sure to fully restart my system in between.
I renamed `~/.config/input-remapper-2` to confirm that my Presets are not the issue.
Due to previous issues I am making sure to not use the chaotic-aur package, instead building from the AUR.
And I have temporarily reverted the kernel update, none of these steps influenced the observed behaviour.

The same issue occurred on my other PC in a larger update (same distro, updated less frequently).
Here restoring a BTRFS snapshot from before the update makes input-remapper.service function again.
I lost the relevant BTRFS snapshot of the system I am writing this report on, but for this report they are comparable.

1. `input-remapper-control --version`
```txt
input-remapper 2.0.1 568f56cdb438f4ad6db9e96b2900d1228ea736ee https://github.com/sezanzeb/input-remapper
python-evdev 1.7.1
```
2. which linux distro (ubuntu 20.04, manjaro, etc.)
Garuda Linux (standard Arch Linux repos plus Chaotic-AUR)
3. `echo $XDG_SESSION_TYPE`
`wayland`
4. which desktop environment (gnome, plasma, xfce4, etc.)
KDE Plasma 6.2.4
5. `sudo ls -l /proc/1/exe`
`lrwxrwxrwx 1 root root 0 Dec 10 22:01 /proc/1/exe -> /usr/lib/systemd/systemd`
6. paste the affected preset .json file from ~/.config/input-remapper-2/presets
*/home/wyvern/.config/input-remapper-2/presets/AT Translated Set 2 keyboard/caps-ctrl-shift-shift.json*
```txt
[
    {
        "input_combination": [
            {
                "type": 1,
                "code": 58,
                "origin_hash": "748e31550c24fc009038438dc4fce338"
            }
        ],
        "target_uinput": "keyboard",
        "output_symbol": "Control_L",
        "mapping_type": "key_macro"
    },
    {
        "input_combination": [
            {
                "type": 1,
                "code": 42,
                "origin_hash": "748e31550c24fc009038438dc4fce338"
            },
            {
                "type": 1,
                "code": 54,
                "origin_hash": "748e31550c24fc009038438dc4fce338"
            }
        ],
        "target_uinput": "keyboard",
        "output_symbol": "Caps_Lock",
        "mapping_type": "key_macro"
    }
]
```
7. `sudo pkill -f input-remapper-service && input-remapper-gtk -d`, apply the preset and hit your key. Then share that log.
```txt
Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/inputremapper/gui/user_interface.py", line 256, in <lambda>
"clicked", lambda *_: self.controller.start_injecting()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/inputremapper/gui/controller.py", line 644, in start_injecting
if not self.data_manager.start_injecting():
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/inputremapper/gui/data_manager.py", line 559, in start_injecting
self._daemon.set_config_dir(self._config.get_dir())
File "/usr/lib/python3.12/site-packages/pydbus/proxy_method.py", line 72, in __call__
ret = instance._bus.con.call_sync(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The nameis not activatable (2)
```
8. `sudo evtest` while the previous command is running, to see how events are injected. Devices starting with `input-remapper ...` are of interest.
No such device is listed:
```txt
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:      Power Button
/dev/input/event1:      Lid Switch
/dev/input/event10:     TPPS/2 Elan TrackPoint
/dev/input/event11:     HD-Audio Generic HDMI/DP,pcm=3
/dev/input/event12:     HD-Audio Generic HDMI/DP,pcm=7
/dev/input/event13:     HD-Audio Generic HDMI/DP,pcm=8
/dev/input/event14:     HD-Audio Generic Mic
/dev/input/event15:     HD-Audio Generic Headphone
/dev/input/event16:     Onboard on-screen keyboard
/dev/input/event2:      Sleep Button
/dev/input/event3:      Power Button
/dev/input/event4:      Video Bus
/dev/input/event5:      Logitech MX Master 2S
/dev/input/event6:      AT Translated Set 2 keyboard
/dev/input/event7:      ThinkPad Extra Buttons
/dev/input/event8:      SynPS/2 Synaptics TouchPad
/dev/input/event9:      Logitech M570
Select the device event number [0-16]:
```

Later this week I am willing to do further troubleshooting, e.g. installing a mainline kernel or downgrading other specific packages.
If this issue "fixes itself" in another update in the meantime, I will report this swiftly.

Thank you for your time, have a nice day!

**Comment by WyvernDotRed** [comment]
**Update:**
Downgrading glib2 from version 2.82.3-1 back to version 2.82.2-1 and doing a full restart fixes the issue, on both my systems.
Do note that this is a forced partial upgrade with the other dependencies and therefore not recommendable.
I do not know whether this is a glib2, input-remapper or some other edge case issue and will leave it at this report for the day.

**Comment by WyvernDotRed** [comment]
**Update:**
The recent glib2 update to version 2.82.3-3 solves the issue on both my systems.
When running `sudo pkill -f input-remapper-service && input-remapper-gtk -d` no errors get logged.
Do again note the need for a system restart to apply this update.

Can @wheat32 and others affected confirm this?
If so, this issue can be closed.

**Comment by amot-dev** [comment]
Can confirm that updating glib2 to 2.82.3-3 has fixed my issues.

**Comment by WyvernDotRed** [comment]
With 3 confirmations that the glib2 update to version 2.82.3-3 solves the issue.
These being on EndeavourOS, Garuda Linux and probably standard Arch Linux.
It seems safe to conclude that this issue has been resolved in this aforementioned update.
So I am closing this issue as solved, thank you all for your time!
