### ISSUE TITLE
Input Remapper not starting

### ISSUE THREAD

**Issue by Aqua1ung** [sezanzeb/input-remapper#1016]
Any idea why this might be happening:
```
Dec 12 22:55:05 DadsGram systemd[2116]: Started app-gnome-input\x2dremapper\x2dgtk-6608.scope.
Dec 12 22:55:05 DadsGram input-remapper-gtk.desktop[6608]: input-remapper-gtk 2.0.1  https://github.com/sezanzeb/input-remapper
Dec 12 22:55:05 DadsGram input-remapper-gtk.desktop[6608]: python-evdev 1.7.1
Dec 12 22:55:07 DadsGram polkitd[687]: Operator of unix-session:2 successfully authenticated as unix-user:dad to gain TEMPORARY authorization for action inputremapper for unix-process:6608:742760 [/usr/bin/python3 /usr/bin/input-remapper>
Dec 12 22:55:07 DadsGram pkexec[6616]: pam_unix(polkit-1:session): session opened for user root(uid=0) by dad(uid=1000)
Dec 12 22:55:07 DadsGram pkexec[6616]: dad: Executing command [USER=root] [TTY=unknown] [CWD=/home/dad] [COMMAND=/usr/bin/input-remapper-control --command start-reader-service]
Dec 12 22:55:07 DadsGram input-remapper-gtk.desktop[6616]: Done
Dec 12 22:55:07 DadsGram input-remapper-gtk.desktop[6608]: Starting the service
Dec 12 22:55:07 DadsGram pkexec[6643]: pam_unix(polkit-1:session): session opened for user root(uid=0) by dad(uid=1000)
Dec 12 22:55:07 DadsGram pkexec[6643]: dad: Executing command [USER=root] [TTY=unknown] [CWD=/home/dad] [COMMAND=/usr/bin/input-remapper-control --command start-daemon]
Dec 12 22:55:07 DadsGram input-remapper-gtk.desktop[6643]: Done
Dec 12 22:55:07 DadsGram input-remapper-gtk.desktop[6651]: ERROR: "/home/dad/.config/input-remapper-2/config.json" does not exist
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6651]: ERROR: "/home/dad/.config/input-remapper-2/config.json" does not exist
Dec 12 22:55:08 DadsGram kernel: input-remapper-[6651]: segfault at 55d8f5dab985 ip 000055ddbc3066de sp 00007ffcbfd12730 error 4 cpu 0 in libgobject-2.0.so.0.8200.3[326de,55ddbc2e4000+5a000] likely on CPU 0 (core 0, socket 0)
Dec 12 22:55:08 DadsGram kernel: Code: 44 e2 fd ff 0f 1f 84 00 00 00 00 00 41 57 41 56 41 55 41 54 55 53 48 83 ec 18 48 85 ff 74 3d 48 8b 07 48 89 fb 48 85 c0 74 32 <48> 8b 00 48 3d fc 03 00 00 77 57 48 c1 e8 02 48 8d 15 2c 9a 05 00
Dec 12 22:55:08 DadsGram systemd[1]: Started systemd-coredump@2-6657-0.service.
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6642]: Found "Sleep Button", "Video Bus", "Wireless hotkeys", "LG WMI hotkeys", "AT Translated Set 2 keyboard", "04CA00B1:00 04CA:00B1 Mouse", "Generic USB Audio", "TESmart DKS202-P24",>
Dec 12 22:55:08 DadsGram systemd-coredump[6658]: [🡕] Process 6651 (input-remapper-) of user 0 dumped core.
                                                 
                                                 Stack trace of thread 6651:
                                                 #0  0x000055ddbc3066de g_type_check_instance_is_fundamentally_a (libgobject-2.0.so.0 + 0x326de)
                                                 #1  0x000055ddbc420018 g_source_callback_unref (libglib-2.0.so.0 + 0x88018)
                                                 #2  0x000055ddbc42229f g_source_destroy_internal (libglib-2.0.so.0 + 0x8a29f)
                                                 #3  0x000055ddbc430db0 g_main_dispatch (libglib-2.0.so.0 + 0x98db0)
                                                 #4  0x000055ddbc4e03bd g_main_context_dispatch_unlocked (libglib-2.0.so.0 + 0x1483bd)
                                                 #5  0x000055ddbc431d5f g_main_loop_run (libglib-2.0.so.0 + 0x99d5f)
                                                 #6  0x000055ddbc2c4052 ffi_call_unix64 (libffi.so.8 + 0xc052)
                                                 #7  0x000055ddbc2c255d ffi_call_int (libffi.so.8 + 0xa55d)
                                                 #8  0x000055ddbc2bd2ad ffi_call (libffi.so.8 + 0x52ad)
                                                 #9  0x000055ddbc5ba224 pygi_invoke_c_callable (_gi.cpython-313-x86_64-linux-gnu.so + 0x3a224)
                                                 #10 0x000055ddbc5b84bd pygi_function_cache_invoke (_gi.cpython-313-x86_64-linux-gnu.so + 0x384bd)
                                                 #11 0x000055ddbc5a6f30 _callable_info_call (_gi.cpython-313-x86_64-linux-gnu.so + 0x26f30)
                                                 #12 0x000055ddbdff151c _PyObject_MakeTpCall (python3.13 + 0x19351c)
                                                 #13 0x000055ddbe00996b _PyEval_EvalFrameDefault (python3.13 + 0x1ab96b)
                                                 #14 0x000055ddbe0c7c29 PyEval_EvalCode (python3.13 + 0x269c29)
                                                 #15 0x000055ddbe0ea490 run_eval_code_obj (python3.13 + 0x28c490)
                                                 #16 0x000055ddbe0e4f5c run_mod (python3.13 + 0x286f5c)
                                                 #17 0x000055ddbe10e005 pyrun_file (python3.13 + 0x2b0005)
                                                 #18 0x000055ddbe10cb7c _PyRun_SimpleFileObject (python3.13 + 0x2aeb7c)
                                                 #19 0x000055ddbe10ef5a _PyRun_AnyFileObject (python3.13 + 0x2b0f5a)
                                                 #20 0x000055ddbe0fc1f4 pymain_run_file_obj (python3.13 + 0x29e1f4)
                                                 #21 0x000055ddbe0b7ee8 Py_BytesMain (python3.13 + 0x259ee8)
                                                 #22 0x000055ddbda29fc7 __libc_start_call_main (libc.so.6 + 0x29fc7)
                                                 #23 0x000055ddbda2a085 __libc_start_main_impl (libc.so.6 + 0x2a085)
                                                 #24 0x000055ddbe0b7321 _start (python3.13 + 0x259321)
                                                 
                                                 Stack trace of thread 6654:
                                                 #0  0x000055ddbdb1b06e __GI_ppoll (libc.so.6 + 0x11b06e)
                                                 #1  0x000055ddbc4e0371 ppoll (libglib-2.0.so.0 + 0x148371)
                                                 #2  0x000055ddbc42fddc g_main_context_iteration (libglib-2.0.so.0 + 0x97ddc)
                                                 #3  0x000055ddbc47d288 g_thread_proxy (libglib-2.0.so.0 + 0xe5288)
                                                 #4  0x000055ddbda9b572 start_thread (libc.so.6 + 0x9b572)
                                                 #5  0x000055ddbdb28438 __clone3 (libc.so.6 + 0x128438)
                                                 
                                                 Stack trace of thread 6655:
                                                 #0  0x000055ddbdb1b06e __GI_ppoll (libc.so.6 + 0x11b06e)
                                                 #1  0x000055ddbc4e0371 ppoll (libglib-2.0.so.0 + 0x148371)
                                                 #2  0x000055ddbc431d5f g_main_loop_run (libglib-2.0.so.0 + 0x99d5f)
                                                 #3  0x000055ddbb1051d6 gdbus_shared_thread_func (libgio-2.0.so.0 + 0x1991d6)
                                                 #4  0x000055ddbc47d288 g_thread_proxy (libglib-2.0.so.0 + 0xe5288)
                                                 #5  0x000055ddbda9b572 start_thread (libc.so.6 + 0x9b572)
                                                 #6  0x000055ddbdb28438 __clone3 (libc.so.6 + 0x128438)
                                                 
                                                 Stack trace of thread 6653:
                                                 #0  0x000055ddbdb25cb9 syscall (libc.so.6 + 0x125cb9)
                                                 #1  0x000055ddbc4826af g_cond_wait_impl (libglib-2.0.so.0 + 0xea6af)
                                                 #2  0x000055ddbc47d288 g_thread_proxy (libglib-2.0.so.0 + 0xe5288)
                                                 #3  0x000055ddbda9b572 start_thread (libc.so.6 + 0x9b572)
                                                 #4  0x000055ddbdb28438 __clone3 (libc.so.6 + 0x128438)
                                                 ELF object binary architecture: AMD x86-64
Dec 12 22:55:08 DadsGram systemd[1]: systemd-coredump@2-6657-0.service: Deactivated successfully.
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]: Traceback (most recent call last):
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:   File "/usr/bin/input-remapper-gtk", line 89, in <module>
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:     daemon = start_processes()
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:   File "/usr/bin/input-remapper-gtk", line 53, in start_processes
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:     return Daemon.connect()
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:            ~~~~~~~~~~~~~~^^
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:   File "/usr/lib/python3.13/site-packages/inputremapper/daemon.py", line 265, in connect
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:     interface.set_config_dir(get_config_path(), timeout=2)
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:     ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:   File "/usr/lib/python3.13/site-packages/pydbus/proxy_method.py", line 72, in __call__
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:     ret = instance._bus.con.call_sync(
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:             instance._bus_name, instance._path,
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:             self._iface_name, self.__name__, GLib.Variant(self._sinargs, args), GLib.VariantType.new(self._soutargs),
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:             0, timeout_to_glib(timeout), None).unpack()
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]: gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (4)
```
Clear Linux 42780, kernel 6.12.4.

**Comment by sezanzeb** [comment]
I don't remember seeing this error unfortunately, sorry

**Comment by WyvernDotRed** [comment]
Seems similar to the recent Arch Linux issue: https://github.com/sezanzeb/input-remapper/issues/1013
What is your glib2 version?
If it's version 2.82.3-1, that explains the issue.
Either downgrade to 2.82.2-1 (or earlier) or upgrade to 2.82.3-3 if available.

On Clear Linux you would have to downgrade the entire system with `sudo swupd repair -m [last working OS version] --force`.
You can forcibly overwrite glib2's installed files if rolling back the entire system is too intrusive.
On other distro's I would not recommend overwriting files like this since it causes issues on updates.
But on Clear Linux `sudo swupd repair --picky` should fix any manually changed files when needed.

**Comment by Aqua1ung** [comment]
> What is your glib2 version?
> 
> If it's version 2.82.3-1, that explains the issue.

That might be it. [Here](https://cdn.download.clearlinux.org/releases/42780/clear/x86_64/os/Packages/) it shows 2.82.3,though I can't tell if it's "-1" or "-2," or "-3."

If that's all there is to it, I'm sure CL people will fix it in the new CL version, and I am happy to wait for now.

Thanks!

**Comment by WyvernDotRed** [comment]
> > What is your glib2 version?
> > If it's version 2.82.3-1, that explains the issue.
> 
> That might be it. [Here](https://cdn.download.clearlinux.org/releases/42780/clear/x86_64/os/Packages/) it shows 2.82.3, though I can't tell if it's "-1" or "-2," or "-3."
> 
> If that's all there is to it, I'm sure CL people will fix it in the new CL version, and I am happy to wait for now.
> 
> Thanks!

This depends on the versioning. The trailing -X numbers indicate builds of minor bugfixes of the same release.
Clear Linux seems to be counting independently of (minor) version numbers, so their 2.82.2-1 is -192, their 2.82.3-1 -193 and if rebuild the fixed version will be -194.

This depends on whether they re-build the -3 revision of glib2.
If they wait for the next version increment or you want it fixed sooner, you can run:
`sudo swupd repair -m 42770 --force` to downgrade to the previous Clear Linux version with glib2 2.82.2.
`swupd autoupdate --disable` to temporarily disable automatic background updates.
And once it is resolved, `swupd autoupdate --enable` to enable said automatic updates again.

--off-topic--
What a coincidence to see someone else also using Clear Linux for a father's laptop!
Even with the same issue I recently reported on my Garuda (Arch-based) system.
On my server I still am a Clear Linux enjoyer, but since I have moved my father's laptop to TuxedoOS, though in a duel-boot with the old Clear Linux installation as a reliable backup.
This move was because document scanning stopped working when we needed it, along with myself having gotten more disillusioned with the current GNOME desktop and not liking how Clear Linux implements KDE Plasma.
Of course all that would have been fixable on Clear Linux too, but on a desktop I would rather not deal with their great but occasionally annoying "stateless" filesystem concept.

**Comment by nuggex** [comment]
I am also having issues starting after I updated and neither the gui nor service start

`
joulu 23 10:54:43 Aries input-remapper-gtk[18539]: Traceback (most recent call last):
joulu 23 10:54:43 Aries input-remapper-gtk[18539]:   File "/usr/bin/input-remapper-gtk", line 38, in <module>
joulu 23 10:54:43 Aries input-remapper-gtk[18539]:     from inputremapper.gui.gettext import _, LOCALE_DIR
joulu 23 10:54:43 Aries input-remapper-gtk[18539]: ModuleNotFoundError: No module named 'inputremapper'
joulu 23 10:54:43 Aries systemd[3967]: app-input\x2dremapper\x2dgtk@78728778f2304a3686b21b3c0f3fef31.service: Main process exited, code=exited, status=1/FAILURE
`

running glib2 2.82.4.2

**Comment by nuggex** [comment]
Removing and cleanbuilding input-remapper-git from Aur fixed the issue for me

**Comment by WyvernDotRed** [comment]
> I am also having issues starting after I updated and neither the gui nor service start
> 
> `joulu 23 10:54:43 Aries input-remapper-gtk[18539]: Traceback (most recent call last): joulu 23 10:54:43 Aries input-remapper-gtk[18539]: File "/usr/bin/input-remapper-gtk", line 38, in <module> joulu 23 10:54:43 Aries input-remapper-gtk[18539]: from inputremapper.gui.gettext import _, LOCALE_DIR joulu 23 10:54:43 Aries input-remapper-gtk[18539]: ModuleNotFoundError: No module named 'inputremapper' joulu 23 10:54:43 Aries systemd[3967]: app-input\x2dremapper\x2dgtk@78728778f2304a3686b21b3c0f3fef31.service: Main process exited, code=exited, status=1/FAILURE`
> 
> running glib2 2.82.4.2

This is an unrelated issue, which I have reported at https://github.com/sezanzeb/input-remapper/issues/1021 now.

**Comment by WyvernDotRed** [comment]
Returning to this issue, it has not yet been resolved by Clear Linux upstream.
The latest Clear Linux build 42800 still has glib-2.82.3-193, which is the affected version.
As found on https://cdn.download.clearlinux.org/releases/42800/clear/x86_64/os/Packages/
after using https://cdn.download.clearlinux.org/releases/ to find the latest release.

**Comment by Aqua1ung** [comment]
> Returning to this issue, it has not yet been resolved by Clear Linux upstream. The latest Clear Linux build 42800 still has glib-2.82.3-193, which is the affected version.
Yeah, looks like Arjan and the boys are taking a bit of a vacation this Christmas, and deservedly so. I guess all we can do at this point is wait.

**Comment by WyvernDotRed** [comment]
Not all you can do. Downgrading still is an option, Clear Linux lets you do that in place.

I just spun up the Clear Linux install still on my father's laptop and ran the downgrade commands I suggested at https://github.com/sezanzeb/input-remapper/issues/1016#issuecomment-2542467618
`sudo swupd autoupdate --disable` and `sudo swupd repair -m 42770 --force`, followed with a reboot and input-remapper should work again.
The commands took a good while to complete and gave a few download errors, which it retried successfully.
After this the system is functional, so I think it can be considered safe to perform this downgrade.

After the fixed glib 2 update has been pushed, running `sudo swupd autoupdate --enable` will make the system continue to update as normal.
If you are not around to manually enable this again, it can be scheduled by putting something like `0 12 * 2 * root swupd autoupdate --enable` in `/etc/cron.d/undo-system-downgrade`.
This example enables automatic updates again at 12:00 on every day in February, to be certain-ish that it will trigger at least once.
Which requires the cronie service to be installed and enabled, I did confirm that cronie applies the setting correctly.

Side-note, I am investigating this so thoroughly because I consider it a preparation for if I have to downgrade the Clear Linux install on my home server.
Of course downgrading the entire OS is not ideal from a security perspective, but it is a good stop-gap solution while waiting for the proper resolution.

**Comment by WyvernDotRed** [comment]
@Aqua1ung, it seems that Clear Linux release 42810 updated to the fixed glib 2.82.4-164 update.
As seen from https://cdn.download.clearlinux.org/releases/42810/clear/x86_64/os/Packages/glib-2.82.4-194.x86_64.rpm
Though `sudo swupd repair -m 42810` fails with `Error: Failed to retrieve 42810 MoM manifest` for now.

The solution is in the pipeline at least, but for the moment Clear Linux stays on the affected 42790 release.
So once release 42810 or later is pushed to the standard updates, input-remapper should work again.

**Comment by Aqua1ung** [comment]
> @Aqua1ung, it seems that Clear Linux release 42810 updated to the fixed glib 2.82.4-164 update.

Thanks. I saw that.
