### ISSUE TITLE
failing tests in main branche

### ISSUE THREAD

**Issue by jonasBoss** [sezanzeb/input-remapper#253]
> I will wait with the GUI test until they work on main.

Tests on main are passing for me. What exactly is failing on your side?

_Originally posted by @sezanzeb in https://github.com/sezanzeb/input-remapper/issues/228#issuecomment-1009971301_

```
======================================================================
FAIL: test_autocomplete_function (testcases.test_gui.TestAutocompletion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 1852, in test_autocomplete_function
    self.add_mapping_via_ui(Key(1, 99, 1), "")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_autocomplete_key (testcases.test_gui.TestAutocompletion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 1809, in test_autocomplete_key
    self.add_mapping_via_ui(Key(1, 99, 1), "")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_close_autocompletion (testcases.test_gui.TestAutocompletion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 1873, in test_close_autocompletion
    self.add_mapping_via_ui(Key(1, 99, 1), "")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_cycling (testcases.test_gui.TestAutocompletion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 1923, in test_cycling
    self.add_mapping_via_ui(Key(1, 99, 1), "")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_writing_still_works (testcases.test_gui.TestAutocompletion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 1894, in test_writing_still_works
    self.add_mapping_via_ui(Key(1, 99, 1), "")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_clears_unreleased_on_focus_change (testcases.test_gui.TestGui)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 785, in test_clears_unreleased_on_focus_change
    self.assertEqual(reader.get_unreleased_keys(), None)
AssertionError: Key((1, 41, 1),) != None

======================================================================
FAIL: test_combination (testcases.test_gui.TestGui)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 890, in test_combination
    self.add_mapping_via_ui(combination_1, "a")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_copy_preset (testcases.test_gui.TestGui)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 1266, in test_copy_preset
    self.add_mapping_via_ui(Key(EV_KEY, 81, 1), "a")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_delete_last_preset (testcases.test_gui.TestGui)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 1772, in test_delete_last_preset
    self.add_mapping_via_ui(Key(1, code, 1), "qux")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_editor (testcases.test_gui.TestGui)
Comprehensive test for the editor.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 806, in test_editor
    self.add_mapping_via_ui(ev_1, "foo_bar")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_editor_simple (testcases.test_gui.TestGui)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 717, in test_editor_simple
    self.assertEqual(len(custom_mapping), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_hat0x (testcases.test_gui.TestGui)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 851, in test_hat0x
    self.add_mapping_via_ui(ev_1, "a")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_problematic_combination (testcases.test_gui.TestGui)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 1013, in test_problematic_combination
    self.add_mapping_via_ui(combination, "b")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_remove_selection_label (testcases.test_gui.TestGui)
Comprehensive test for selection_labels 2.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 993, in test_remove_selection_label
    selection_label_1 = self.add_mapping_via_ui(Key(EV_KEY, 10, 1), "a")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_shared_presets (testcases.test_gui.TestGui)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 1750, in test_shared_presets
    self.add_mapping_via_ui(Key(3, 2, 1), "qux")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_start_injecting (testcases.test_gui.TestGui)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 1533, in test_start_injecting
    self.add_mapping_via_ui(Key(EV_KEY, keycode_from, 1), "a")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

======================================================================
FAIL: test_stop_injecting (testcases.test_gui.TestGui)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 1635, in test_stop_injecting
    self.add_mapping_via_ui(Key(EV_KEY, keycode_from, 1), "t")
  File "/home/jonas/dev/key-mapper/tests/testcases/test_gui.py", line 391, in add_mapping_via_ui
    self.assertFalse(self.toggle.get_active())
AssertionError: True is not false

----------------------------------------------------------------------
Ran 294 tests in 50.115s

FAILED (failures=17)
```

**Comment by jonasBoss** [comment]
It is an Environment issue. When running the tests from the PyCharm console, the input-remapper window does not get the focus. 
If there is a way to tell the DE to focus a window it would be a good Idea for the tests. 

When running the tests in a different terminal emulator everything works.

**Comment by sezanzeb** [comment]
ah, good to know

**Comment by sezanzeb** [comment]
It is now possible to run tests via PyCharms built in tools. There is an "All Tests" configuration now.
