### ISSUE TITLE
could not open uinput device in write mode

### ISSUE THREAD

**Issue by xyamazing69** [sezanzeb/input-remapper#256]
The error:

```
Process Injector-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/site-packages/inputremapper/injection/injector.py", line 377, in run
    self.context.uinput = evdev.UInput(
  File "/usr/lib/python3.10/site-packages/evdev/uinput.py", line 130, in __init__
    self.fd = _uinput.open(devnode)
OSError: could not open uinput device in write mode
ERROR: Injector was unexpectedly found stopped
```

Version: input-remapper 1.3.0 47bcefa7f382abc4c7b00cc9876262406c1615d2 https://github.com/sezanzeb/input-remapper

python-evdev 1.4.0

Distro: Arch

session type:x11

de: kde plasma

```
ls -l /proc/1/exe: lrwxrwxrwx 1 root root 0 Jan 13 15:11 /proc/1/exe -> /usr/lib/systemd/systemd
mapping:
{
    "mapping": {
        "1,276,1": "KEY_F13",
        "1,275,1": "KEY_F14"
    }
}
```

pkill could not find any devices

**Comment by sezanzeb** [comment]
Please post the output of

```
lsmod | grep uinput
ls -l /dev/uinput
```

**Comment by sezanzeb** [comment]
closing due to inactivity
