### ISSUE TITLE
Some tests can fail under high CPU load

### ISSUE THREAD

**Issue by LunNova** [sezanzeb/input-remapper#306]
Some tests check how long something took to happen or otherwise depend on being on a low load system and fail when a system is heavily loaded.

```
======================================================================
FAIL: test_wheel (unit.test_injector.TestInjector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 83, in _callMaybeAsync
    ret = func(*args, **kwargs)
  File "/build/source/tests/unit/test_injector.py", line 700, in test_wheel
    self.assertAlmostEqual(
AssertionError: 0.06462240219116211 != 0.05 within 0.01 delta (0.014622402191162107 difference)

======================================================================
FAIL: test_debounce_1 (unit.test_keycode_mapper.TestKeycodeMapper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 87, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 101, in _asyncioLoopRunner
    ret = await awaitable
  File "/build/source/tests/unit/test_keycode_mapper.py", line 1251, in test_debounce_1
    self.assertEqual(len(self.history), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_debounce_2 (unit.test_keycode_mapper.TestKeycodeMapper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 87, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 101, in _asyncioLoopRunner
    ret = await awaitable
  File "/build/source/tests/unit/test_keycode_mapper.py", line 1272, in test_debounce_2
    self.assertEqual(len(self.history), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_debounce_3 (unit.test_keycode_mapper.TestKeycodeMapper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 87, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 101, in _asyncioLoopRunner
    ret = await awaitable
  File "/build/source/tests/unit/test_keycode_mapper.py", line 1288, in test_debounce_3
    self.assertEqual(len(self.history), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_hold (unit.test_keycode_mapper.TestKeycodeMapper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 87, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 101, in _asyncioLoopRunner
    ret = await awaitable
  File "/build/source/tests/unit/test_keycode_mapper.py", line 666, in test_hold
    self.assertGreater(len(self.history), events * 0.9)
AssertionError: 44 not greater than 46.800000000000004

======================================================================
FAIL: test_hold_two (unit.test_keycode_mapper.TestKeycodeMapper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 87, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 101, in _asyncioLoopRunner
    ret = await awaitable
  File "/build/source/tests/unit/test_keycode_mapper.py", line 916, in test_hold_two
    self.assertGreater(len(self.history), events * 0.9)
AssertionError: 88 not greater than 93.60000000000001

======================================================================
FAIL: test_2 (unit.test_macros.TestMacros)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 87, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/async_case.py", line 101, in _asyncioLoopRunner
    ret = await awaitable
  File "/build/source/tests/unit/test_macros.py", line 665, in test_2
    self.assertLess(time.time() - start, sleep_time * 1.2)
AssertionError: 0.519057035446167 not less than 0.48
```

Not sure how easy it would be to improve this, I would like to look into this more if I have some time.

**Comment by sezanzeb** [comment]
Maybe we can add a cli argument that changes how some tests work. Timing checks are then skipped, or the test keeps sleeping until the required number of events has been injected (with a timeout of maybe two seconds).

**Comment by LunNova** [comment]
I've been super busy recently and intend to look at this when I have some more time.

**Comment by sezanzeb** [comment]
No pressure, thanks a lot for what you have already done for input-remapper!
