### ISSUE TITLE
window not open

### ISSUE THREAD

**Issue by vadim212112** [sezanzeb/input-remapper#317]
Manjaro linux 21.2.4
linux kernel 5.15.25
kde plasma 5.24.2
kde framework 5.91

in terminal show error
`input-remapper-gtk
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 36, in <module>
    gi.require_version('GtkSource', '4')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available
`

**Comment by sezanzeb** [comment]
Did you install this from the AUR? `pacaur -S input-remapper-git`?
