### ISSUE TITLE
Failed to start input-mapper.service due to: TypeError: dataclass() got an unexpected keyword argument 'slots'

### ISSUE THREAD

**Issue by wkoszycki** [sezanzeb/input-remapper#326]
Hi I have tried to install and run version from main branch 
```
commit 180bf5aa418e773923865d62c4c1b37c3865506f (HEAD -> main, tag: 1.4.1, origin/main, origin/HEAD)
Author: sezanzeb <proxima@sezanzeb.de>
Date:   Sun Feb 27 20:57:33 2022 +0100

    1.4.1
```
I was following instructions from README.md however encounterd following issue:
```
mar 02 07:54:56 wk-ubuntu systemd[1]: Starting Service to inject keycodes without the GUI application...
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]: Traceback (most recent call last):
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]:   File "/usr/bin/input-remapper-service", line 47, in <module>
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]:     from inputremapper.daemon import Daemon
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]:   File "/usr/local/lib/python3.8/dist-packages/inputremapper/daemon.py", line 41, in <module>
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]:     from inputremapper.injection.injector import Injector, UNKNOWN
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]:   File "/usr/local/lib/python3.8/dist-packages/inputremapper/injection/injector.py", line 33, in <module>
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]:     from inputremapper.configs.preset import Preset
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]:   File "/usr/local/lib/python3.8/dist-packages/inputremapper/configs/preset.py", line 37, in <module>
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]:     from inputremapper.event_combination import EventCombination
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]:   File "/usr/local/lib/python3.8/dist-packages/inputremapper/event_combination.py", line 32, in <module>
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]:     from inputremapper.input_event import InputEvent
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]:   File "/usr/local/lib/python3.8/dist-packages/inputremapper/input_event.py", line 30, in <module>
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]:     @dataclass(frozen=True, slots=True)
mar 02 07:54:56 wk-ubuntu input-remapper-service[257922]: TypeError: dataclass() got an unexpected keyword argument 'slots'
mar 02 07:54:56 wk-ubuntu systemd[1]: input-remapper.service: Main process exited, code=exited, status=1/FAILURE
mar 02 07:54:56 wk-ubuntu systemd[1]: input-remapper.service: Failed with result 'exit-code'.
mar 02 07:54:56 wk-ubuntu systemd[1]: Failed to start Service to inject keycodes without the GUI application.
```

Please advise

**Comment by sezanzeb** [comment]
the code in the stack trace is outdated, it seems you are not running the latest version in `/usr/local/lib/python3.8/dist-packages/inputremapper/`

Try to uninstall it such that the files in there are gone, and then reinstall it

**Comment by sezanzeb** [comment]
I'm going to close this for now, since the problem seems to be quite clear here

**Comment by wkoszycki** [comment]
Thx @sezanzeb it worked
