### ISSUE TITLE
Can't pip install in Gentoo

### ISSUE THREAD

**Issue by tunerooster** [sezanzeb/input-remapper#340]
I installed using:
```
sudo pip install --no-binary :all: git+https://github.com/sezanzeb/input-remapper.git --user
Collecting git+https://github.com/sezanzeb/input-remapper.git
  Cloning https://github.com/sezanzeb/input-remapper.git to /tmp/pip-req-build-b5mn1fyn
  Running command git clone --filter=blob:none --quiet https://github.com/sezanzeb/input-remapper.git /tmp/pip-req-build-b5mn1fyn
  Resolved https://github.com/sezanzeb/input-remapper.git to commit 754e252567ba73d620ea49ee58b68086799c7837
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /usr/lib/python3.10/site-packages (from input-remapper==1.4.1) (60.9.2)
Requirement already satisfied: evdev in /home/rwk/.local/lib/python3.10/site-packages (from input-remapper==1.4.1) (1.4.0)
Requirement already satisfied: pydbus in /home/rwk/.local/lib/python3.10/site-packages (from input-remapper==1.4.1) (0.6.0)
Requirement already satisfied: pygobject in /usr/lib/python3.10/site-packages (from input-remapper==1.4.1) (3.42.0)
Requirement already satisfied: pydantic in /home/rwk/.local/lib/python3.10/site-packages (from input-remapper==1.4.1) (1.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/rwk/.local/lib/python3.10/site-packages (from pydantic->input-remapper==1.4.1) (4.1.1)
Skipping wheel build for input-remapper, due to binaries being disabled for it.
Installing collected packages: input-remapper
  Running setup.py install for input-remapper ... done
Successfully installed input-remapper-1.4.1
```
When I then run:
```
/usr/bin/input-remapper-gtk
```
After authenticating, I get the following error:
```
input-remapper-gtk 1.4.1 754e252567ba73d620ea49ee58b68086799c7837 https://github.com/sezanzeb/input-remapper
python-evdev 1.4.0
Loaded config from "/home/rwk/.config/input-remapper/config.json"
Starting the service
Traceback (most recent call last):
  File "/usr/bin/input-remapper-control", line 30, in <module>
    from inputremapper.logger import logger, update_verbosity, log_info, add_filehandler
ModuleNotFoundError: No module named 'inputremapper'
ERROR: Failed to connect to the service
```
Two issues:
1. ModuleNotFoundError: No module named 'inputremapper'
2. ERROR: Failed to connect to the service

Can anyone help me with this?  Thanks!!!

**Comment by sezanzeb** [comment]
don't install with --user

**Comment by tunerooster** [comment]
My OS (gentoo) will not allow install without --user, saying it will otherwise confilict with the gentoo package manager.

I have also successfully installed as root but the same thing happens.  This also requires --user.

All --user does is install it in $HOME/.local which should not affect anything other than where is eexcutes from.

Please advise...

**Comment by tunerooster** [comment]
I found this directory:
```
/home/rwk/.local/lib/python3.10/site-packages/inputremapper
```
I also confirmed the following:
```
Python 3.10.2 (main, Mar  9 2022, 04:07:15) [GCC 11.2.1 20220115] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/rwk/.local/lib/python3.10/site-packages', '/usr/lib/python3.10/site-packages']
>>> import inputremapper
>>>
```
Notice that I am able to import inputremapper from the python REPL loop.  But from :
```/usr/bin/input-remapper-gtk``` I get the ModuleNotFound error.  I.e., whether run as rwk (my user name) or as root.

Can you suggest a fix?

Thanks!

**Comment by tunerooster** [comment]
UPDATE:

OK, this time I ran:
```
sudo su
pip install --no-binary :all: git+https://github.com/sezanzeb/input-remapper.git --user
```
Whereas before I ran:
```
sudo pip install --no-binary :all: git+https://github.com/sezanzeb/input-remapper.git --user
```
Apparently there is a difference.  This time it installed in ```/root/.local``` and last time it installed in ```/home/rwk/.local```.
Now when I run (as root) ```/usr/bin/input-remapper-gtk``` I get:
```
input-remapper-gtk 1.4.1 754e252567ba73d620ea49ee58b68086799c7837 https://github.com/sezanzeb/input-remapper
python-evdev 1.4.0
Creating dir "/tmp/input-remapper-rwk"
Loaded config from "/home/rwk/.config/input-remapper/config.json"
Starting the service
Starting logging to "/var/log/input-remapper-control"
Done
Starting logging to "/var/log/input-remapper"
Loaded config from "/home/rwk/.config/input-remapper/config.json"
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/evdev/uinput.py", line 264, in _verify
    m = os.stat(self.devnode)[stat.ST_MODE]
FileNotFoundError: [Errno 2] No such file or directory: '/dev/uinput'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/input-remapper-service", line 53, in <module>
    daemon = Daemon()
  File "/root/.local/lib/python3.10/site-packages/inputremapper/daemon.py", line 186, in __init__
    global_uinputs.prepare()
  File "/root/.local/lib/python3.10/site-packages/inputremapper/injection/global_uinputs.py", line 98, in prepare
    self.devices[name] = self._uinput_factory(
  File "/root/.local/lib/python3.10/site-packages/inputremapper/injection/global_uinputs.py", line 50, in __init__
    super().__init__(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/evdev/uinput.py", line 127, in __init__
    self._verify()
  File "/root/.local/lib/python3.10/site-packages/evdev/uinput.py", line 270, in _verify
    raise UInputError(msg.format(self.devnode))
evdev.uinput.UInputError: "/dev/uinput" does not exist or is not a character device file - verify that the uinput module is loaded
Stopping all injections
ERROR: Failed to connect to the service
```
I.e., I no longer get the ModuleNotFound error.
So I ran: ```/usr/bin/input-remapper-service``` as root and got:
```
Starting logging to "/var/log/input-remapper"
input-remapper-service 1.4.1 754e252567ba73d620ea49ee58b68086799c7837 https://github.com/sezanzeb/input-remapper
python-evdev 1.4.0
Loaded config from "/home/rwk/.config/input-remapper/config.json"
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/evdev/uinput.py", line 264, in _verify
    m = os.stat(self.devnode)[stat.ST_MODE]
FileNotFoundError: [Errno 2] No such file or directory: '/dev/uinput'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/input-remapper-service", line 53, in <module>
    daemon = Daemon()
  File "/root/.local/lib/python3.10/site-packages/inputremapper/daemon.py", line 186, in __init__
    global_uinputs.prepare()
  File "/root/.local/lib/python3.10/site-packages/inputremapper/injection/global_uinputs.py", line 98, in prepare
    self.devices[name] = self._uinput_factory(
  File "/root/.local/lib/python3.10/site-packages/inputremapper/injection/global_uinputs.py", line 50, in __init__
    super().__init__(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/evdev/uinput.py", line 127, in __init__
    self._verify()
  File "/root/.local/lib/python3.10/site-packages/evdev/uinput.py", line 270, in _verify
    raise UInputError(msg.format(self.devnode))
evdev.uinput.UInputError: "/dev/uinput" does not exist or is not a character device file - verify that the uinput module is loaded
Stopping all injections
```
The referenced log file just repeats the message above.

I don't know what ```/dev/uinput``` is, but I see that I *DO* have the evdev module and it does import from the repl loop, if that is related.

Can you suggest what I need to do?  I think I am close!!!

What is supposed to start the "service"?  I didn't see anything in the README.

**Comment by sezanzeb** [comment]
> No such file or directory: '/dev/uinput'

`sudo modprobe uinput`

> What is supposed to start the "service"? I didn't see anything in the README.

The service is started via https://github.com/sezanzeb/input-remapper/blob/main/data/input-remapper.service

**Comment by sezanzeb** [comment]
> if I run: /usr/bin/input-remapper-gtk as root, shouldn't it work?

no, this is just the user interface, which already managed to import the module since it runs as your user. GTK applications should not run as root by the way, see: https://wiki.archlinux.org/title/Running_GUI_applications_as_root

> Apparently there is a difference

yes, $USER and $HOME (and potentially more) environment variables keep pointing to your user when using sudo

**Comment by tunerooster** [comment]
I added CONFIG_INPUT_UINPUT to my kernel and how I have a /dev/uinput. 


I am not running systemd (I use openrc), but I find that running /usr/bin/input-remapper-service starts the service.

In now runs as root, but fails to run (ModuleNotFound error) as rwk (ny user id).  I tried:
```
PYTHONPATH=/root/.local/lib/python3.10/site-packages /usr/bin/input-remapper-gtk
```
But still get:
```Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 28, in <module>
    from inputremapper.gui.gettext import _, LOCALE_DIR
ModuleNotFoundError: No module named 'inputremapper'
```
Is there maybe something more I need to add to the python path?  The path (as root) is:
```
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/root/.local/lib/python3.10/site-packages', '/usr/lib/python3.10/site-packages']
```
Which works.

The path as "rwk" is:
```
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/rwk/.local/lib/python3.10/site-packages', '/usr/lib/python3.10/site-packages']
```
Which fails.

I only need to run this once or twice and I am behind a strong firewall, so I don't think I am worried much about the gtk as root warning.  

However, if you have any suggestions how I might get it running as a plain user, please advise.

Thanks for your help!!!

**Comment by tunerooster** [comment]
UPDATE:

I just found that running:
```
HOME=/root PYTHONPATH=/root/.local/lib/python3.10/site-packages sys /usr/bin/input-remapper-gtk
```
allows me to run as rwk!

Kind of klugy, but it works!

**Comment by sezanzeb** [comment]
do you have read permission for `/root/.local/lib/python3.10/site-packages`? I can't read into `/root` on my system

also make sure to use `export PYTHONPATH`

**Comment by sezanzeb** [comment]
any updates? Should this be closed? If gentoo doesn't allow global pip installation I frankly have no idea how to properly support gentoo

**Comment by sezanzeb** [comment]
I'll close this for now. Feel free to comment here again if you are still facing issues

**Comment by tunerooster** [comment]
I got it to work, but only as root, but that's all I needed.  Thanks for
your help!
