### ISSUE TITLE
failed to apply preset

### ISSUE THREAD

**Issue by moebek** [sezanzeb/input-remapper#343]
Hi, 

I am using Fedora 35 x11 with gnome. Today I installed input-remapper with pip and it fails to apply the settings for my Logitech G502 mouse. Below is the systemctl log. Let me know if further details is needed.

```
Traceback (most recent call last):
   File "/usr/lib64/python3.10/multiprocessing/process.py", line 315, in _bootstrap
     self.run()
   File "/usr/local/lib/python3.10/site-packages/inputremapper/injection/injector.py", line 331, in run
     forward_to = evdev.UInput(
 TypeError: UInput.__init__() got an unexpected keyword argument 'input_props'
```

**Comment by sezanzeb** [comment]
related to https://github.com/sezanzeb/input-remapper/issues/336

fix is on the way
