### ISSUE TITLE
GUI start failed in GNOME/gtk

### ISSUE THREAD

**Issue by zomen2** [sezanzeb/input-remapper#349]
Hi!

On Arch linux:

```shell
[zomen@tapsi ~]$ input-remapper-gtk 
input-remapper-gtk 1.4.2 af20f87a1298153e765b840a2164ba63b9ef937a https://github.com/sezanzeb/input-remapper
python-evdev 1.4.0
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 58, in <module>
    from inputremapper.gui.user_interface import UserInterface
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/user_interface.py", line 57, in <module>
    from inputremapper.gui.editor.editor import Editor
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/editor/editor.py", line 36, in <module>
    from inputremapper.gui.reader import reader
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/reader.py", line 252, in <module>
    reader = Reader()
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/reader.py", line 75, in __init__
    self.connect()
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/reader.py", line 79, in connect
    self._results = Pipe(f"/tmp/input-remapper-{USER}/results")
  File "/usr/lib/python3.10/site-packages/inputremapper/ipc/pipe.py", line 72, in __init__
    chown(f"{fds_dir}{self._fds[0]}")
  File "/usr/lib/python3.10/site-packages/inputremapper/configs/paths.py", line 35, in chown
    shutil.chown(path, user=USER, group=USER)
  File "/usr/lib/python3.10/shutil.py", line 1332, in chown
    os.chown(path, _user, _group)
PermissionError: [Errno 1] Operation not permitted: '/proc/13630/fd/15'
```

**Comment by sezanzeb** [comment]
try

```
sudo rm /tmp/input-remapper-*/ -R
sudo systemctl restart input-remapper
input-remapper-gtk
```

**Comment by zomen2** [comment]
Hi,

Thank for your quick response.

I have seen the source and the /tmp directory after program exit and I have played a little bit with the program.
I think there are at least two issue.

I started the service with systemctl. Installed python version is: Python 3.10.2

1)
I removed the "/tmp/input-remapper-zomen" directory. After the first start of gtk program I got this stack trace what is different from that I sent when I opened the ticket.

```
[zomen@tapsi ~]$ input-remapper-gtk 
input-remapper-gtk 1.4.2 af20f87a1298153e765b840a2164ba63b9ef937a https://github.com/sezanzeb/input-remapper
python-evdev 1.4.0
Creating dir "/tmp/input-remapper-zomen"
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 58, in <module>
    from inputremapper.gui.user_interface import UserInterface
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/user_interface.py", line 57, in <module>
    from inputremapper.gui.editor.editor import Editor
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/editor/editor.py", line 36, in <module>
    from inputremapper.gui.reader import reader
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/reader.py", line 252, in <module>
    reader = Reader()
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/reader.py", line 75, in __init__
    self.connect()
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/reader.py", line 79, in connect
    self._results = Pipe(f"/tmp/input-remapper-{USER}/results")
  File "/usr/lib/python3.10/site-packages/inputremapper/ipc/pipe.py", line 59, in __init__
    mkdir(os.path.dirname(path))
  File "/usr/lib/python3.10/site-packages/inputremapper/configs/paths.py", line 75, in mkdir
    chown(path)
  File "/usr/lib/python3.10/site-packages/inputremapper/configs/paths.py", line 35, in chown
    shutil.chown(path, user=USER, group=USER)
  File "/usr/lib/python3.10/shutil.py", line 1332, in chown
    os.chown(path, _user, _group)
PermissionError: [Errno 1] Operation not permitted: '/tmp/input-remapper-zomen'
```

What could be happened?

configs/paths.py:74 mkdir successfully creates the directory.
```
drwxr-xr-x 2 zomen users 40 Mar 21 11:46 input-remapper-zomen
```
after that:

configs/paths.py:75 wants to change ownership on this directory, but it fails. Finally "os.chown(path, _user, _group)" statement threw an exception. I don't understand why? Why fails a no-op in python? In [python manual](https://docs.python.org/3/library/os.html#os.chown) there is a suspicious sentence: "Raises an auditing event os.chown with arguments path, uid, gid, dir_fd."
The current implementation handles only "LookupError" at configs/paths.py:36.
I think it would be better if the program checked  the ownership of this directory and exit with result code and an error message on  stderr (instead of exception). It is not typical that a specifically-named directory has different ownership, so I would allow the user to tidy up his/her filesystem.

2)

After first run that described above, I got the same error as I have written when I opened this issue. So really this issue are two issue, but maybe the root cause is the same.

I looked into the proc filesystem and I found that fd files of a running process have right ownership. Ie.  it is not necessary to change by the program. And I see that fd files are really symlinks.

**Comment by sezanzeb** [comment]
why does it say "zoomen users"? I think on all my installations there was always a group called like my user.

**Comment by sezanzeb** [comment]
> What could be happened?

First the folder will be created, then the pipes. Since the directories are gone, the folder needs to be recreated

> After first run that described above, I got the same error as I have written when I opened this issue

Because the folder exists and now the pipes are being created

> So really this issue are two issue, but maybe the root cause is the same.

Only a single issue here

**Comment by sezanzeb** [comment]
Run `input-remapper-gtk -d` please so that I can verify who is trying to create the pipes

**Comment by sezanzeb** [comment]
> Is the daemon part of the remapper creates files/directories/pipes under the temp dir?

no, it is a different process. a helper that starts via pkexec and has root permissions.

> The group and other have no write right to the temp directory

They should: https://unix.stackexchange.com/questions/71622/what-are-correct-permissions-for-tmp-i-unintentionally-set-it-all-public-recu

```
➜  /tmp ls -l / | grep tmp
drwxrwxrwt  25 root root   800 21. Mär 14:30 tmp
```

**Comment by sezanzeb** [comment]
> So, if the helper process creates the temp directory and has root rights then it should set permission and ownership on the temp directory and sub-items. But it does not do.

The helper process does not create the directory, as verified by the logs:

```
14:07:20.588812 12739 GUI DEBUG pipe.py:62: Creating new pipe for "/tmp/input-remapper-zomen/results"
```

> Who starts the helper process?
> Where is it in the source?

`def start_processes` in user_interface.py

Please tell me what the output of this command is: `/tmp ls -l / | grep tmp`

**Comment by sezanzeb** [comment]
Does the [ignore-permission-errors](https://github.com/sezanzeb/input-remapper/tree/ignore-permission-errors) branch work for you?
