### ISSUE TITLE
Namespace GtkSource not available

### ISSUE THREAD

**Issue by LCARngr** [sezanzeb/input-remapper#350]
I have installed input-mapper using pip on a Fedora 34 machine.
the install seemed to go fine.  I have run it both with sudo and normal, here is the output:

```
[lcames@Lynn-TwrPC ~]$ sudo input-remapper-gtk -d
[sudo] password for lcames: 
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 33, in <module>
    gi.require_version('GtkSource', '4')
  File "/usr/lib64/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available
[lcames@Lynn-TwrPC ~]$ input-remapper-gtk -d
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 33, in <module>
    gi.require_version('GtkSource', '4')
  File "/usr/lib64/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available
```

I did previously install key-remapper, but I did follow the uninstall step for it during installation of input-remapper.

I have installed the most current Fedora updates just today actually. I installed input-remapper today.

```
[lcames@Lynn-TwrPC ~]$ uname -a
Linux Lynn-TwrPC 5.16.15-101.fc34.x86_64 #1 SMP PREEMPT Thu Mar 17 05:50:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by sezanzeb** [comment]
Do you have `gtksourceview4` installed like the readme says?

**Comment by LCARngr** [comment]
Hi,  I added the necessary packages and the gui is working. Thank You
