### ISSUE TITLE
"ValueError: Invalid file descriptor: -1" after --list-devices

### ISSUE THREAD

**Issue by DreadPirateLynx** [sezanzeb/input-remapper#352]
The above command suddenly started producing the following output along with the requested list after an update today:
```
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fb933595870>
Traceback (most recent call last):
File "/usr/lib/python3.10/asyncio/base_events.py", line 682, in __del__
self.close()
File "/usr/lib/python3.10/asyncio/unix_events.py", line 68, in close
super().close()
File "/usr/lib/python3.10/asyncio/selector_events.py", line 92, in close
self._close_self_pipe()
File "/usr/lib/python3.10/asyncio/selector_events.py", line 99, in _close_self_pipe
self._remove_reader(self._ssock.fileno())
File "/usr/lib/python3.10/asyncio/selector_events.py", line 277, in _remove_reader
key = self._selector.get_key(fd)
File "/usr/lib/python3.10/selectors.py", line 191, in get_key
return mapping[fileobj]
File "/usr/lib/python3.10/selectors.py", line 72, in __getitem__
fd = self._selector._fileobj_lookup(fileobj)
File "/usr/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
return _fileobj_to_fd(fileobj)
File "/usr/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
```

**Comment by DreadPirateLynx** [comment]
This seems to have disappeared in the most recent update
