### ISSUE TITLE
Gui works fine but nothing changes after pressing "apply".

### ISSUE THREAD

**Issue by rcgalvao** [sezanzeb/input-remapper#372]
```
09:06:59.947697 50229 GUI DEBUG reader.py:162: down ·························· <InputEvent ['BTN_LEFT', 'BTN_MOUSE'] (272) down>
09:06:59.947858 50229 GUI DEBUG reader.py:182: read result ··················· <EventCombination (1, 272, 1)>
09:06:59.947960 50229 GUI DEBUG editor.py:597: Recording toggle is not on
09:07:00.068480 50229 GUI DEBUG editor.py:337: Enabling the text input
09:07:00.068932 50229 GUI DEBUG editor.py:337: Enabling the text input
09:07:00.080895 50229 GUI DEBUG reader.py:147: release ······················· <InputEvent ['BTN_LEFT', 'BTN_MOUSE'] (272) up>
09:07:02.733688 50229 GUI DEBUG reader.py:162: down ·························· <InputEvent ['BTN_LEFT', 'BTN_MOUSE'] (272) down>
09:07:02.849469 50229 GUI DEBUG user_interface.py:747: Not saving because preset did not change
09:07:02.849561 50229 GUI INFO user_interface.py:530: Applying preset "Laterais" for "Corsair CORSAIR HARPOON RGB PRO Gaming Mouse"
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/user_interface.py", line 117, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/user_interface.py", line 565, in on_apply_preset_clicked
    self.dbus.start_injecting(self.group.key, preset)
  File "/usr/lib/python3.10/site-packages/pydbus/proxy_method.py", line 72, in __call__
    ret = instance._bus.con.call_sync(
gi.repository.GLib.GError: g-io-error-quark: GDBus.Error:unknown.OSError: could not open uinput device in write mode (36)
```

**Comment by sezanzeb** [comment]
complete log please

**Comment by sezanzeb** [comment]
closing due to inactivity
