### ISSUE TITLE
Version 1.5 stop working randomly

### ISSUE THREAD

**Issue by darkfrank-it** [sezanzeb/input-remapper#424]
After update to 1.5 input-remapper stop working randomly. 
It appears to be blocking mouse input. if I use xev the input is taken after several clicks.

Share some logs please:

1. `input-remapper-control --version`

```
input-remapper 1.5.0 e31a1b2bc5d23fe13130afcc242063196335399f https://github.com/sezanzeb/input-remapper
python-evdev 1.4.0
```

3. which linux distro (ubuntu 20.04, manjaro, etc.)

```
OS: Lubuntu 22.04 LTS x86_64
Kernel: 5.15.51-051551-generic
```
5. `echo $XDG_SESSION_TYPE`

```
x11
```

7. which desktop environment (gnome, plasma, xfce4, etc.)

```
DE: LXQt 1.1.1
WM: Openbox
```

9. `sudo ls -l /proc/1/exe`

```
lrwxrwxrwx 1 root root 0 lug  1 08:41 /proc/1/exe -> /usr/lib/systemd/systemd
```

11. paste the affected preset .json file from ~/.config/input-remapper/presets

```
{
    "mapping": {
        "1,276,1": [
            "Control_L+c",
            "keyboard"
        ],
        "1,275,1": [
            "Control_R+v",
            "keyboard"
        ]
    }
}
```

12. `sudo pkill -f input-remapper-service && input-remapper-gtk -d`, start the injection and hit your key. Then share that log.

```
16:47:52.239182 51298 GUI INFO logger.py:223: input-remapper-gtk 1.5.0 e31a1b2bc5d23fe13130afcc242063196335399f https://github.com/sezanzeb/input-remapper                                                                                                                                                  
16:47:52.239252 51298 GUI INFO logger.py:231: python-evdev 1.4.0
16:47:52.239280 51298 GUI WARNING logger.py:234: Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!                                                                                                       
16:47:52.239305 51298 GUI DEBUG input-remapper-gtk:55: Using locale directory: /usr/share/input-remapper/lang
16:47:52.241815 51298 GUI DEBUG pipe.py:62: Creating new pipe for "/tmp/input-remapper-nicola/results"
16:47:52.242085 51298 GUI DEBUG pipe.py:62: Creating new pipe for "/tmp/input-remapper-nicola/commands"
16:47:52.249160 51298 GUI DEBUG migrations.py:254: Failed to remove deprecated logfiles: [Errno 13] Permission denied: '/var/log/input-remapper'
16:47:52.249248 51298 GUI INFO global_config.py:105: Loaded config from "/home/nicola/.config/input-remapper/config.json"
16:47:52.250664 51298 GUI INFO daemon.py:205: Starting the service
16:47:52.250713 51298 GUI DEBUG daemon.py:216: Running `pkexec input-remapper-control --command start-daemon  -d`
16:47:55.024481 51302 Control DEBUG input-remapper-control:230: Call for "['/usr/bin/input-remapper-control', '--command', 'start-daemon', '-d']"
16:47:55.027741 51302 Control DEBUG input-remapper-control:212: Booting finished
16:47:55.028276 51302 Control INFO input-remapper-control:260: Done
16:47:55.144107 51311 Service DEBUG daemon.py:166: Creating daemon
16:47:55.144259 51311 Service INFO global_config.py:105: Loaded config from "/home/nicola/.config/input-remapper/config.json"
16:47:55.144310 51311 Service DEBUG shared_dict.py:57: Starting SharedDict process
16:47:55.145797 51312 Service DEBUG shared_dict.py:63: SharedDict process started
16:47:55.149037 51311 Service DEBUG daemon.py:252: Running daemon
16:47:55.247915 51298 GUI DEBUG daemon.py:235: Telling service about "/home/nicola/.config/input-remapper"
16:47:55.250347 51311 Service INFO global_config.py:105: Loaded config from "/home/nicola/.config/input-remapper/config.json"
16:47:55.251335 51298 GUI DEBUG user_interface.py:246: Running `pkexec input-remapper-control --command helper  -d`
16:47:58.330322 51316 Control DEBUG input-remapper-control:230: Call for "['/usr/bin/input-remapper-control', '--command', 'helper', '-d']"
16:47:58.333874 51316 Control DEBUG input-remapper-control:212: Booting finished
16:47:58.334328 51316 Control INFO input-remapper-control:260: Done
16:47:58.349031 51298 GUI DEBUG global_uinputs.py:80: creating fake UInput device: 'input-remapper keyboard'
16:47:58.349183 51298 GUI DEBUG global_uinputs.py:80: creating fake UInput device: 'input-remapper gamepad'
16:47:58.349228 51298 GUI DEBUG global_uinputs.py:80: creating fake UInput device: 'input-remapper mouse'
16:47:58.349267 51298 GUI DEBUG global_uinputs.py:80: creating fake UInput device: 'input-remapper keyboard + mouse'
16:47:58.442462 51298 GUI DEBUG groups.py:337: Discovering device paths
16:47:58.443052 51298 GUI DEBUG groups.py:446: Did not find any input device
16:47:58.447674 51324 GUI-Helper DEBUG pipe.py:79: Using existing pipe for "/tmp/input-remapper-nicola/results"
16:47:58.447814 51324 GUI-Helper DEBUG pipe.py:79: Using existing pipe for "/tmp/input-remapper-nicola/commands"
16:47:58.447885 51324 GUI-Helper DEBUG helper.py:110: Sending groups
16:47:58.449034 51324 GUI-Helper DEBUG groups.py:337: Discovering device paths
16:47:58.449974 51324 GUI-Helper DEBUG groups.py:378: Found "24_1267_12649_i2c-ELAN073B:00", "/dev/input/event16", "ELAN073B:00 04F3:3169 Touchpad", type: touchpad                                                                                                                                         
16:47:58.450108 51324 GUI-Helper DEBUG groups.py:378: Found "24_1267_12649_i2c-ELAN073B:00", "/dev/input/event15", "ELAN073B:00 04F3:3169 Mouse", type: unknown                                                                                                                                             
16:47:58.450300 51324 GUI-Helper DEBUG groups.py:378: Found "25_0_0_wmi", "/dev/input/event5", "HP WMI hotkeys", type: unknown
16:47:58.450412 51324 GUI-Helper DEBUG groups.py:378: Found "25_0_0_-", "/dev/input/event14", "Intel HID events", type: unknown
16:47:58.450511 51324 GUI-Helper DEBUG groups.py:378: Found "25_0_0_hpq6001", "/dev/input/event13", "Wireless hotkeys", type: unknown
16:47:58.450756 51324 GUI-Helper DEBUG groups.py:378: Found "3_5215_611_usb-0000:00:14.0-6", "/dev/input/event11", "MOSART Semi. Trust Wireless Mouse", type: mouse                                                                                                                                         
16:47:58.450865 51324 GUI-Helper DEBUG groups.py:378: Found "3_1133_49948_usb-0000:00:14.0-4", "/dev/input/event10", "Logitech USB Keyboard System Control", type: unknown                                                                                                                                  
16:47:58.450973 51324 GUI-Helper DEBUG groups.py:378: Found "3_1133_49948_usb-0000:00:14.0-4", "/dev/input/event9", "Logitech USB Keyboard Consumer Control", type: unknown                                                                                                                                 
16:47:58.451125 51324 GUI-Helper DEBUG groups.py:378: Found "3_1133_49948_usb-0000:00:14.0-4", "/dev/input/event8", "Logitech USB Keyboard", type: keyboard                                                                                                                                                 
16:47:58.451227 51324 GUI-Helper DEBUG groups.py:378: Found "25_0_6_LNXVIDEO", "/dev/input/event7", "Video Bus", type: unknown
16:47:58.451371 51324 GUI-Helper DEBUG groups.py:378: Found "17_1_1_isa0060", "/dev/input/event4", "AT Translated Set 2 keyboard", type: keyboard
16:47:58.451643 51324 GUI-Helper DEBUG groups.py:378: Found "25_0_3_PNP0C0E", "/dev/input/event0", "Sleep Button", type: unknown
16:47:58.451925 51324 GUI-Helper INFO groups.py:449: Found "ELAN073B:00 04F3:3169 Mouse", "HP WMI hotkeys", "Intel HID events", "Wireless hotkeys", "MOSART Semi. Trust Wireless Mouse", "Logitech USB Keyboard", "Video Bus", "AT Translated Set 2 keyboard", "Sleep Button"                               
16:47:58.452058 51324 GUI-Helper DEBUG helper.py:91: Waiting for the first command
16:47:58.497615 51298 GUI DEBUG reader.py:99: Received 9 devices
16:47:58.499830 51298 GUI DEBUG preset.py:379: The newest preset is "MOSART Semi. Trust Wireless Mouse", "copycat"
16:47:58.500221 51298 GUI DEBUG user_interface.py:600: Selecting device "MOSART Semi. Trust Wireless Mouse"
16:47:58.500580 51298 GUI DEBUG user_interface.py:384: "MOSART Semi. Trust Wireless Mouse" presets: "copycat"
16:47:58.501170 51298 GUI DEBUG user_interface.py:714: Selecting preset "copycat"
16:47:58.502268 51298 GUI DEBUG editor.py:322: Disabling the text input
16:47:58.503211 51298 GUI DEBUG editor.py:322: Disabling the text input
16:47:58.503936 51298 GUI INFO preset.py:170: Loading preset from "/home/nicola/.config/input-remapper/presets/MOSART Semi. Trust Wireless Mouse/copycat.json"                                                                                                                                              
16:47:58.504167 51298 GUI DEBUG preset.py:200: <EventCombination (1, 276, 1)> maps to ('Control_L+c', 'keyboard')
16:47:58.504251 51298 GUI DEBUG preset.py:200: <EventCombination (1, 275, 1)> maps to ('Control_R+v', 'keyboard')
16:47:58.504823 51298 GUI DEBUG system_mapping.py:91: Gathering available keycodes
16:47:58.504882 51298 GUI DEBUG system_mapping.py:91: Gathering available keycodes
16:47:58.506512 51298 GUI DEBUG system_mapping.py:120: Writing "/home/nicola/.config/input-remapper/xmodmap.json"
16:47:58.506754 51298 GUI DEBUG system_mapping.py:91: Gathering available keycodes
16:47:58.514192 51298 GUI DEBUG system_mapping.py:120: Writing "/home/nicola/.config/input-remapper/xmodmap.json"
16:47:58.518083 51298 GUI DEBUG system_mapping.py:120: Writing "/home/nicola/.config/input-remapper/xmodmap.json"
16:47:58.519774 51298 GUI DEBUG editor.py:337: Enabling the text input
16:47:58.520326 51298 GUI DEBUG editor.py:337: Enabling the text input
16:47:58.520656 51298 GUI DEBUG reader.py:190: Sending start msg to helper for "MOSART Semi. Trust Wireless Mouse"
16:47:58.520730 51298 GUI DEBUG reader.py:206: Clearing reader
16:47:58.520823 51324 GUI-Helper DEBUG helper.py:103: Starting mainloop
16:47:58.520916 51324 GUI-Helper DEBUG helper.py:117: Received command "MOSART Semi. Trust Wireless Mouse"
16:47:58.520961 51324 GUI-Helper DEBUG helper.py:139: No more commands in pipe
16:47:58.521043 51324 GUI-Helper DEBUG helper.py:174: Starting reading keycodes from "MOSART Semi. Trust Wireless Mouse"
16:47:58.621162 51298 GUI DEBUG autocompletion.py:91: get_incomplete_parameter text:  match: None
16:47:59.022791 51298 GUI DEBUG parse.py:350: Transformed "Control_L+c" to "hold_keys(Control_L,c)"
16:47:59.022961 51298 GUI DEBUG parse.py:427: checking the syntax of hold_keys(Control_L,c)
16:47:59.023376 51298 GUI DEBUG parse.py:273: calls hold_keys with Control_L,c
16:47:59.023851 51298 GUI DEBUG parse.py:330:   string Control_L
16:47:59.023968 51298 GUI DEBUG parse.py:330:   string c
16:47:59.024075 51298 GUI DEBUG parse.py:294: add call to hold_keys with ['Control_L', 'c'], {}
16:47:59.024390 51298 GUI DEBUG parse.py:350: Transformed "Control_R+v" to "hold_keys(Control_R,v)"
16:47:59.024498 51298 GUI DEBUG parse.py:427: checking the syntax of hold_keys(Control_R,v)
16:47:59.024660 51298 GUI DEBUG parse.py:273: calls hold_keys with Control_R,v
16:47:59.024779 51298 GUI DEBUG parse.py:330:   string Control_R
16:47:59.024908 51298 GUI DEBUG parse.py:330:   string v
16:47:59.025010 51298 GUI DEBUG parse.py:294: add call to hold_keys with ['Control_R', 'v'], {}
16:47:59.701299 51298 GUI DEBUG reader.py:162: down ·························· <InputEvent BTN_EXTRA (276) down>
16:47:59.701633 51298 GUI DEBUG reader.py:182: read result ··················· <EventCombination (1, 276, 1)>
16:47:59.701809 51298 GUI DEBUG editor.py:597: Recording toggle is not on
16:47:59.869347 51298 GUI DEBUG reader.py:147: release ······················· <InputEvent BTN_EXTRA (276) up>
16:48:00.237701 51298 GUI DEBUG reader.py:162: down ·························· <InputEvent BTN_SIDE (275) down>
16:48:00.237835 51298 GUI DEBUG reader.py:182: read result ··················· <EventCombination (1, 275, 1)>
16:48:00.237910 51298 GUI DEBUG editor.py:597: Recording toggle is not on
16:48:00.371060 51298 GUI DEBUG reader.py:147: release ······················· <InputEvent BTN_SIDE (275) up>
16:48:05.144590 51298 GUI DEBUG reader.py:162: down ·························· <InputEvent BTN_EXTRA (276) down>
16:48:05.144882 51298 GUI DEBUG reader.py:182: read result ··················· <EventCombination (1, 276, 1)>
16:48:05.145028 51298 GUI DEBUG editor.py:597: Recording toggle is not on
16:48:05.345541 51298 GUI DEBUG reader.py:147: release ······················· <InputEvent BTN_EXTRA (276) up>
16:48:06.082540 51298 GUI DEBUG reader.py:162: down ·························· <InputEvent BTN_SIDE (275) down>
16:48:06.082921 51298 GUI DEBUG reader.py:182: read result ··················· <EventCombination (1, 275, 1)>
16:48:06.083130 51298 GUI DEBUG editor.py:597: Recording toggle is not on
16:48:06.249990 51298 GUI DEBUG reader.py:147: release ······················· <InputEvent BTN_SIDE (275) up>
^CTraceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 76, in <module>
    Gtk.main()
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1678, in main
    with register_sigint_fallback(Gtk.main_quit):
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt
16:48:07.788840 51298 GUI DEBUG user_interface.py:332: Closing window
16:48:07.789343 51298 GUI DEBUG reader.py:197: Sending close msg to helper

(input-remapper-gtk:51298): Gtk-CRITICAL **: 16:48:07.789: gtk_main_quit: assertion 'main_loops != NULL' failed
16:48:07.789730 51324 GUI-Helper DEBUG helper.py:193: Stops reading due to new command
16:48:07.790529 51324 GUI-Helper DEBUG helper.py:117: Received command "terminate"
16:48:07.790648 51324 GUI-Helper DEBUG helper.py:120: Helper terminates
```

13. `sudo evtest` would also be interesting while the first command is still running, to see how your mappings are injected.

```
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x145f product 0x263 version 0x110
Input device name: "MOSART Semi. Trust Wireless Mouse"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 274 (BTN_MIDDLE)
    Event code 275 (BTN_SIDE)
    Event code 276 (BTN_EXTRA)
  Event type 2 (EV_REL)
    Event code 0 (REL_X)
    Event code 1 (REL_Y)
    Event code 6 (REL_HWHEEL)
    Event code 8 (REL_WHEEL)
    Event code 11 (REL_WHEEL_HI_RES)
    Event code 12 (REL_HWHEEL_HI_RES)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
Event: time 1656687208.020088, type 2 (EV_REL), code 0 (REL_X), value 1
Event: time 1656687208.020088, -------------- SYN_REPORT ------------
Event: time 1656687208.036004, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1656687208.036004, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 1
Event: time 1656687208.036004, -------------- SYN_REPORT ------------
Event: time 1656687208.180109, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1656687208.180109, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 0
Event: time 1656687208.180109, -------------- SYN_REPORT ------------
Event: time 1656687209.140119, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1656687209.140119, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1656687209.140119, -------------- SYN_REPORT ------------
Event: time 1656687209.300012, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1656687209.300012, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0
Event: time 1656687209.300012, -------------- SYN_REPORT ------------
Event: time 1656687210.896097, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1656687210.896097, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 1
Event: time 1656687210.896097, -------------- SYN_REPORT ------------
Event: time 1656687211.088106, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1656687211.088106, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 0
Event: time 1656687211.088106, -------------- SYN_REPORT ------------
Event: time 1656687211.216031, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1656687211.216031, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 1
Event: time 1656687211.216031, -------------- SYN_REPORT ------------
Event: time 1656687211.360047, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1656687211.360047, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 0
Event: time 1656687211.360047, -------------- SYN_REPORT ------------
Event: time 1656687211.848029, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1656687211.848029, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1656687211.848029, -------------- SYN_REPORT ------------
Event: time 1656687211.992039, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1656687211.992039, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0
Event: time 1656687211.992039, -------------- SYN_REPORT ------------
Event: time 1656687212.104095, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1656687212.104095, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1656687212.104095, -------------- SYN_REPORT ------------
Event: time 1656687212.264082, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1656687212.264082, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0
Event: time 1656687212.264082, -------------- SYN_REPORT ------------
```

**Comment by sezanzeb** [comment]
Thanks for providing all of the information

> It appears to be blocking mouse input. if I use xev the input is taken after several clicks.

what do you mean with "taken"?

So you can't move your mouse anymore?

There should be something like a `input-remapper MOSART Semi. Trust Wireless Mouse forwarded`, please use evtest on that one. I'll update the issue template because this is what I usually need to see

**Comment by darkfrank-it** [comment]
I mean xev receive the input (and make the log) after several clicks of button 4 or 5.

Here the evtest

```
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x145f product 0x263 version 0x110
Input device name: "input-remapper MOSART Semi. Trust Wireless Mouse forwarded"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 274 (BTN_MIDDLE)
    Event code 275 (BTN_SIDE)
    Event code 276 (BTN_EXTRA)
  Event type 2 (EV_REL)
    Event code 0 (REL_X)
    Event code 1 (REL_Y)
    Event code 6 (REL_HWHEEL)
    Event code 8 (REL_WHEEL)
    Event code 11 (REL_WHEEL_HI_RES)
    Event code 12 (REL_HWHEEL_HI_RES)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
  Event type 21 (EV_FF)
Properties:
Testing ... (interrupt to exit)
Event: time 1656762528.941439, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1656762528.941439, -------------- SYN_REPORT ------------
Event: time 1656762529.149347, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1656762529.149347, -------------- SYN_REPORT ------------
Event: time 1656762530.389466, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1656762530.389466, -------------- SYN_REPORT ------------
^CEvent: time 1656762530.761348, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1656762530.761348, -------------- SYN_REPORT ------------
Event: time 1656762533.685393, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1656762533.685393, -------------- SYN_REPORT ------------
^V^V^V^VEvent: time 1656762534.388846, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1656762534.388846, -------------- SYN_REPORT ------------
Event: time 1656762535.193410, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1656762535.193410, -------------- SYN_REPORT ------------
```

 

**Anyway it seems that the problem has gone after i made a clean install of the 1.5 version. 
I would close the issue, it probably wasn't an input-remapper problem.**

**Comment by sezanzeb** [comment]
> Anyway it seems that the problem has gone after i made a clean install of the 1.5 version.

Surprising. But yeah lets close it then.

If you are facing the issue again please feel free to comment here again.

So did I understand correctly that the two problems you had were:
1. The `Control_L + c` mapping only worked after several clicks
2. you were not able to move the mouse cursor while input-remapper was injecting a preset

?
