### ISSUE TITLE
input-remapper service error since I updated from python 3.9 to python 3.10 (gentoo) - It was working fine with python 3.9

### ISSUE THREAD

**Issue by Mat9999** [sezanzeb/input-remapper#426]
Please install the newest version from source to see if the problem has already been solved.
Done from git

**System Information and logs**

1. `input-remapper-control --version`
Could not figure out the version
input-remapper  d7f15d15249314c73b29f0a502733ad231bb09b8 https://github.com/sezanzeb/input-remapper

2. which linux distro (ubuntu 20.04, manjaro, etc.)
Gentoo

3. which desktop environment (gnome, plasma, xfce4, etc.)
Plasma 5.25.2

4. `sudo ls -l /proc/1/exe` to check if you are using systemd
lrwxrwxrwx 1 root root 0  4 juil. 20:31 /proc/1/exe -> /lib/systemd/systemd

5. `cat ~/.config/input-remapper/config.json` to see if the "autoload" config is written correctly

{
    "version": "",
    "autoload": {
        "Logitech USB Receiver": "new preset"
    },
    "macros": {
        "keystroke_sleep_ms": 10
    },
    "gamepad": {
        "joystick": {
            "non_linearity": 4,
            "pointer_speed": 80,
            "left_purpose": "none",
            "right_purpose": "none",
            "x_scroll_speed": 2,
            "y_scroll_speed": 0.5
        }
    }
}

6. `systemctl status input-remapper -n 50` the service has to be running
●input-remapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/input-remapper.service; enabled; vendor preset: disabled)
     Active: active (running) since Wed 2022-07-06 20:14:14 CEST; 1min 17s ago
   Main PID: 235293 (python3)
      Tasks: 4 (limit: 77049)
     Memory: 27.5M
        CPU: 176ms
     CGroup: /system.slice/input-remapper.service
             ├─ 235293 /usr/lib/python-exec/python3.10/python3 /usr/bin/input-remapper-service
             └─ 235295 /usr/lib/python-exec/python3.10/python3 /usr/bin/input-remapper-service

juil. 06 20:14:14 goldorak.actarus systemd[1]: Starting Service to inject keycodes without the GUI application...
juil. 06 20:14:14 goldorak.actarus input-remapper-service[235293]: Could not figure out the version
juil. 06 20:14:14 goldorak.actarus input-remapper-service[235293]: input-remapper-service  d7f15d15249314c73b29f0a502733ad231bb09b8 https://github.com/sezanzeb/input-remapper
juil. 06 20:14:14 goldorak.actarus systemd[1]: Started Service to inject keycodes without the GUI application.

**Testing the setup**

1. `input-remapper-control --command hello`
Could not figure out the version
Connected to the service
/usr/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Daemon answered with "hello"
Done

2. `sudo pkill -f input-remapper-service && sudo input-remapper-service -d & sleep 2 && input-remapper-control --command autoload`, are your keys mapped now?
no:
Logs from service:
Could not figure out the version
20:27:58.374313 240053 Service INFO logger.py:223: input-remapper-service  d7f15d15249314c73b29f0a502733ad231bb09b8 https://github.com/sezanzeb/input-remapper
20:27:58.374370 240053 Service WARNING logger.py:234: Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
20:27:58.374409 240053 Service DEBUG daemon.py:166: Creating daemon
20:27:58.374519 240053 Service INFO global_config.py:105: Loaded config from "/home/mathieu/.config/input-remapper/config.json"
20:27:58.374564 240053 Service DEBUG shared_dict.py:57: Starting SharedDict process
20:27:58.376157 240054 Service DEBUG shared_dict.py:63: SharedDict process started
20:27:58.380163 240053 Service DEBUG daemon.py:252: Running daemon
20:28:31.410858 240053 Service INFO global_config.py:105: Loaded config from "/home/mathieu/.config/input-remapper/config.json"
20:28:31.411411 240053 Service INFO global_config.py:105: Loaded config from "/home/mathieu/.config/input-remapper/config.json"
20:28:31.413448 240053 Service INFO daemon.py:398: Autoloading for all devices
20:28:31.413506 240053 Service DEBUG daemon.py:265: Refreshing because last info is too old
20:28:31.514442 240053 Service DEBUG groups.py:337: Discovering device paths
20:28:31.516121 240053 Service DEBUG groups.py:378: Found "3_1_1_py-evdev-uinput", "/dev/input/event27", "solaar-keyboard", type: keyboard
20:28:31.595971 240053 Service DEBUG groups.py:378: Found "3_1133_2746_usb-0000:0f:00.3-3", "/dev/input/event6", "Logitech PRO X Wireless Gaming Headset Consumer Control", type: unknown
20:28:32.002761 240053 Service DEBUG groups.py:378: Found "3_5426_103_usb-0000:08:00.3-2.4", "/dev/input/event11", "Razer Razer Naga Trinity", type: keyboard
20:28:32.086352 240053 Service DEBUG groups.py:378: Found "3_5426_103_usb-0000:08:00.3-2.4", "/dev/input/event9", "Razer Razer Naga Trinity Keyboard", type: keyboard
20:28:32.106419 240053 Service DEBUG groups.py:378: Found "3_5426_103_usb-0000:08:00.3-2.4", "/dev/input/event8", "Razer Razer Naga Trinity", type: mouse
20:28:32.125979 240053 Service DEBUG groups.py:378: Found "3_1133_50504_usb-0000:08:00.1-1", "/dev/input/event5", "Logitech USB Receiver System Control", type: unknown
20:28:32.156041 240053 Service DEBUG groups.py:378: Found "3_1133_50504_usb-0000:08:00.1-1", "/dev/input/event4", "Logitech USB Receiver Consumer Control", type: unknown
20:28:32.179373 240053 Service DEBUG groups.py:378: Found "3_1133_50504_usb-0000:08:00.1-1", "/dev/input/event3", "Logitech USB Receiver Mouse", type: mouse
20:28:32.199361 240053 Service DEBUG groups.py:378: Found "3_1133_50504_usb-0000:08:00.1-1", "/dev/input/event2", "Logitech USB Receiver", type: keyboard
20:28:32.242930 240053 Service INFO groups.py:449: Found "solaar-keyboard", "Logitech PRO X Wireless Gaming Headset Consumer Control", "Razer Razer Naga Trinity", "Logitech USB Receiver"
20:28:32.243055 240053 Service INFO daemon.py:343: Autoloading for "Logitech USB Receiver"
20:28:32.243126 240053 Service INFO daemon.py:420: Request to start injecting for "Logitech USB Receiver"
20:28:32.243213 240053 Service INFO preset.py:170: Loading preset from "/home/mathieu/.config/input-remapper/presets/Logitech USB Receiver/new preset.json"
20:28:32.243396 240053 Service DEBUG preset.py:200: <EventCombination (1, 277, 1)> maps to ('KEY_LEFTMETA + KEY_PAGEUP', 'mouse')
20:28:32.243506 240053 Service DEBUG global_uinputs.py:60: creating UInput device: 'input-remapper mouse'
20:28:32.344517 240053 Service DEBUG daemon.py:472: Using keycodes from "/home/mathieu/.config/input-remapper/xmodmap.json"
20:28:32.344620 240053 Service DEBUG system_mapping.py:91: Gathering available keycodes
20:28:32.344699 240053 Service DEBUG system_mapping.py:91: Gathering available keycodes
20:28:32.348052 240053 Service DEBUG system_mapping.py:144: Updated keycodes with 0 new ones
20:28:32.349752 240193 Service INFO injector.py:301: Starting injecting the preset for "Logitech USB Receiver"
20:28:32.350222 240193 Service DEBUG context.py:90: Parsing macros
20:28:32.350492 240193 Service DEBUG parse.py:350: Transformed "KEY_LEFTMETA+KEY_PAGEUP" to "hold_keys(KEY_LEFTMETA,KEY_PAGEUP)"
20:28:32.350541 240193 Service DEBUG parse.py:429: preparing macro hold_keys(KEY_LEFTMETA,KEY_PAGEUP) for later execution
20:28:32.350755 240193 Service DEBUG parse.py:273: calls hold_keys with KEY_LEFTMETA,KEY_PAGEUP
20:28:32.350955 240193 Service DEBUG parse.py:330:   string KEY_LEFTMETA
20:28:32.351010 240193 Service DEBUG parse.py:330:   string KEY_PAGEUP
20:28:32.351054 240193 Service DEBUG parse.py:294: add call to hold_keys with ['KEY_LEFTMETA', 'KEY_PAGEUP'], {}
20:28:32.351404 240193 Service DEBUG injector.py:211: No need to grab /dev/input/event5
20:28:32.392890 240193 Service DEBUG injector.py:211: No need to grab /dev/input/event4
20:28:32.429366 240193 Service DEBUG injector.py:198: Grabbing "/dev/input/event3" because of "<EventCombination (1, 277, 1)>"
20:28:32.429477 240193 Service DEBUG injector.py:218: Grab /dev/input/event3
20:28:32.429644 240193 Service DEBUG injector.py:211: No need to grab /dev/input/event2
20:28:32.574561 240193 Service DEBUG numlock.py:66: numlockx not found
20:28:32.574930 240193 Service DEBUG consumer_control.py:86: Starting to listen for events from /dev/input/event3, fd 26
Process Group(Logitech USB Receiver):
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/site-packages/inputremapper/injection/injector.py", line 369, in run
    loop.run_until_complete(asyncio.gather(*coroutines))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/inputremapper/injection/consumer_control.py", line 93, in run
    if event.type == evdev.ecodes.EV_KEY and event.value == 2:
AttributeError: '_asyncio.Future' object has no attribute 'type'

Logs from input-remapper-control --command autoload
Could not figure out the version
Connected to the service
/usr/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Autoloading all
Done

3. (while the previous command is still running) `sudo evtest` and search for a device suffixed by "mapped". Select it, does it report any events? Share the output.
I dont see device suffixed by mapped:
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:      Power Button
/dev/input/event1:      Power Button
/dev/input/event2:      Logitech USB Receiver
/dev/input/event3:      Logitech USB Receiver Mouse
/dev/input/event4:      Logitech USB Receiver Consumer Control
/dev/input/event5:      Logitech USB Receiver System Control
/dev/input/event6:      Logitech PRO X Wireless Gaming Headset Consumer Control
/dev/input/event7:      Logitech PRO X Wireless Gaming Headset
/dev/input/event8:      Razer Razer Naga Trinity
/dev/input/event9:      Razer Razer Naga Trinity Keyboard
/dev/input/event10:     Razer Razer Naga Trinity
/dev/input/event11:     Razer Razer Naga Trinity
/dev/input/event12:     PC Speaker
/dev/input/event13:     HDA ATI HDMI HDMI/DP,pcm=3
/dev/input/event14:     HDA ATI HDMI HDMI/DP,pcm=7
/dev/input/event15:     HDA ATI HDMI HDMI/DP,pcm=8
/dev/input/event16:     HDA ATI HDMI HDMI/DP,pcm=9
/dev/input/event17:     HDA ATI HDMI HDMI/DP,pcm=10
/dev/input/event18:     HDA ATI HDMI HDMI/DP,pcm=11
/dev/input/event19:     Eee PC WMI hotkeys
/dev/input/event20:     HD-Audio Generic Front Mic
/dev/input/event21:     HD-Audio Generic Rear Mic
/dev/input/event22:     HD-Audio Generic Line
/dev/input/event23:     HD-Audio Generic Line Out Front
/dev/input/event24:     HD-Audio Generic Line Out Surround
/dev/input/event25:     HD-Audio Generic Line Out CLFE
/dev/input/event26:     HD-Audio Generic Front Headphone
/dev/input/event27:     solaar-keyboard
/dev/input/event28:     input-remapper mouse
Select the device event number [0-28]:
I tried 28, but nothing happens 

4. `sudo udevadm control --log-priority=debug && sudo udevadm control --reload-rules && journalctl -f | grep input-remapper`, now plug in the device that should autoload
udevadm control --log-priority=debug && sudo udevadm control --reload-rules && journalctl -f | grep input-remapper
juil. 06 20:33:01 goldorak.actarus systemd-udevd[1496]: Reading rules file: /usr/lib/udev/rules.d/99-input-remapper.rules
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241213]: input49: /usr/lib/udev/rules.d/99-input-remapper.rules:10 RUN '/bin/input-remapper-control --command autoload --device $env{DEVNAME}'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241213]: input49: Running command "/bin/input-remapper-control --command autoload --device "
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241213]: input49: Starting '/bin/input-remapper-control --command autoload --device '
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241213]: input49: Process '/bin/input-remapper-control --command autoload --device ' failed with exit code 1.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241213]: input49: Command "/bin/input-remapper-control --command autoload --device " returned 1 (error), ignoring.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241222]: input50: /usr/lib/udev/rules.d/99-input-remapper.rules:10 RUN '/bin/input-remapper-control --command autoload --device $env{DEVNAME}'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241222]: input50: Running command "/bin/input-remapper-control --command autoload --device "
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241222]: input50: Starting '/bin/input-remapper-control --command autoload --device '
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241222]: input50: Process '/bin/input-remapper-control --command autoload --device ' failed with exit code 1.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241222]: input50: Command "/bin/input-remapper-control --command autoload --device " returned 1 (error), ignoring.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241228]: input51: /usr/lib/udev/rules.d/99-input-remapper.rules:10 RUN '/bin/input-remapper-control --command autoload --device $env{DEVNAME}'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241229]: input52: /usr/lib/udev/rules.d/99-input-remapper.rules:10 RUN '/bin/input-remapper-control --command autoload --device $env{DEVNAME}'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241228]: input51: Running command "/bin/input-remapper-control --command autoload --device "
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241228]: input51: Starting '/bin/input-remapper-control --command autoload --device '
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241229]: input52: Running command "/bin/input-remapper-control --command autoload --device "
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241229]: input52: Starting '/bin/input-remapper-control --command autoload --device '
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241228]: input51: Process '/bin/input-remapper-control --command autoload --device ' failed with exit code 1.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241229]: input52: Process '/bin/input-remapper-control --command autoload --device ' failed with exit code 1.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241228]: input51: Command "/bin/input-remapper-control --command autoload --device " returned 1 (error), ignoring.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241229]: input52: Command "/bin/input-remapper-control --command autoload --device " returned 1 (error), ignoring.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241213]: mouse0: /usr/lib/udev/rules.d/99-input-remapper.rules:10 RUN '/bin/input-remapper-control --command autoload --device $env{DEVNAME}'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241213]: mouse0: Running command "/bin/input-remapper-control --command autoload --device /dev/input/mouse0"
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241213]: mouse0: Starting '/bin/input-remapper-control --command autoload --device /dev/input/mouse0'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241213]: mouse0: Process '/bin/input-remapper-control --command autoload --device /dev/input/mouse0' failed with exit code 1.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241213]: mouse0: Command "/bin/input-remapper-control --command autoload --device /dev/input/mouse0" returned 1 (error), ignoring.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241234]: event2: /usr/lib/udev/rules.d/99-input-remapper.rules:10 RUN '/bin/input-remapper-control --command autoload --device $env{DEVNAME}'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241234]: event2: Running command "/bin/input-remapper-control --command autoload --device /dev/input/event2"
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241234]: event2: Starting '/bin/input-remapper-control --command autoload --device /dev/input/event2'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241234]: event2: Process '/bin/input-remapper-control --command autoload --device /dev/input/event2' failed with exit code 1.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241234]: event2: Command "/bin/input-remapper-control --command autoload --device /dev/input/event2" returned 1 (error), ignoring.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241228]: event4: /usr/lib/udev/rules.d/99-input-remapper.rules:10 RUN '/bin/input-remapper-control --command autoload --device $env{DEVNAME}'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241229]: event5: /usr/lib/udev/rules.d/99-input-remapper.rules:10 RUN '/bin/input-remapper-control --command autoload --device $env{DEVNAME}'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241229]: event5: Running command "/bin/input-remapper-control --command autoload --device /dev/input/event5"
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241229]: event5: Starting '/bin/input-remapper-control --command autoload --device /dev/input/event5'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241228]: event4: Running command "/bin/input-remapper-control --command autoload --device /dev/input/event4"
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241228]: event4: Starting '/bin/input-remapper-control --command autoload --device /dev/input/event4'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241229]: event5: Process '/bin/input-remapper-control --command autoload --device /dev/input/event5' failed with exit code 1.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241229]: event5: Command "/bin/input-remapper-control --command autoload --device /dev/input/event5" returned 1 (error), ignoring.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241228]: event4: Process '/bin/input-remapper-control --command autoload --device /dev/input/event4' failed with exit code 1.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241228]: event4: Command "/bin/input-remapper-control --command autoload --device /dev/input/event4" returned 1 (error), ignoring.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241238]: event3: /usr/lib/udev/rules.d/99-input-remapper.rules:10 RUN '/bin/input-remapper-control --command autoload --device $env{DEVNAME}'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241238]: event3: Running command "/bin/input-remapper-control --command autoload --device /dev/input/event3"
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241238]: event3: Starting '/bin/input-remapper-control --command autoload --device /dev/input/event3'
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241238]: event3: Process '/bin/input-remapper-control --command autoload --device /dev/input/event3' failed with exit code 1.
juil. 06 20:33:07 goldorak.actarus systemd-udevd[241238]: event3: Command "/bin/input-remapper-control --command autoload --device /dev/input/event3" returned 1 (error), ignoring.

**Comment by jonasBoss** [comment]
At first glance this seems to be related to `python-evdev`. Which version of `python-evdev` do you have installed?

**Comment by Mat9999** [comment]
python-evdev 1.5.0

**Comment by jonasBoss** [comment]
That is the newest version. So shouldn't be the issue.
But from the error you get this seems to be the offending package.

>File "/usr/lib/python3.10/site-packages/inputremapper/injection/consumer_control.py", line 93, in run
if event.type == evdev.ecodes.EV_KEY and event.value == 2:
AttributeError: '_asyncio.Future' object has no attribute 'type'

For context this is line 92 and 93: 
```python
async for event in self._source.async_read_loop():
    if event.type == evdev.ecodes.EV_KEY and event.value == 2:
        ...
```
`async_read_loop()` is a function form python-evdev which returns a `asyncio.Future` object. This is then awaite by the async for loop.
So either the python-evedev is somehow broken or python itself. 

I'm purely guessing right now:
On my system when I install a new python, the old `/usr/lib/python3.x/site-packages` is not remove and python3.10 happily uses packages installed to python3.8 or 3.9
So maybe you have multiple version of a package in the different paths installed. Maybe you can go though the paths and see if you have a duplicate install of evdev and or input-remapper.

Also your input-remapper install seems to be unable to figure out which version is installed, suggesting that there might be an issue with the input-remapper installation. There should be a
`/usr/lib/python3.10/site-packages/input_remapper-1.5.0-py3.10.egg-info/` folder containing all the package information.

**Comment by jonasBoss** [comment]
If you have python3.9 still installed can you run
`sudo pkill -f input-remapper-service && sudo python3.9 input-remapper-service -d & sleep 2 && python3.9 input-remapper-control --command autoload` and post the logs?

**Comment by Mat9999** [comment]
Python packages are managed via portage,  the gentoo package manager. There is only one version of python and python-evdev installed for now, even if it is possible to install both 3.10 and 3.9 versions, but I'm not sure how easy it is to do it.

For the installation of input-remapper, I did it via setup.py install.
There is a /usr/lib/python3.10/site-packages/input_remapper-1.5.0-py3.10.egg-info/ directory:
```
# ls /usr/lib/python3.10/site-packages/input_remapper-1.5.0-py3.10.egg-info/
dependency_links.txt  PKG-INFO  requires.txt  SOURCES.txt  top_level.txt
```

**Comment by jonasBoss** [comment]
can you run the following script with sudo:

```python
#!/usr/bin/python3

import evdev
import asyncio

# use the device number of your keyboard ($sudo evtest to find it)
device = evdev.InputDevice("/dev/input/eventXX") 

async def run():
    async for event in device.async_read_loop():
        print(event)

asyncio.run(run())
```
it should print out the keyboard events as you press keys.
If not there is something wrong with python or evdev. If it works there is something wrong with input-remapper

**Comment by Mat9999** [comment]
It's displaying  "Future Pending" very fast, but does not react to key press:
``
 ./test.py 
<Future pending>
<Future pending>
<Future pending>
<Future pending>
<Future pending>
<Future pending>
<Future pending>
<Future pending>
<Future pending>
<Future pending>
<Future pending>
<Future pending>
<Future pending>
<Future pending>
<Future pending>
``
Thank you very much for your time.
I will not be available during the 20 next hours.

**Comment by jonasBoss** [comment]
That eliminates Input-Remapper as the problem.

**Comment by Mat9999** [comment]
Ok, I have reinstalled python and python-evdev with no errors, but no success with the test script.
If it is python install related, I will close this ticket, I can't ask you to support my system problems.

**Comment by Mat9999** [comment]
Ok, I have reinstalled python and python-evdev with no errors, but no success with the test script.
If it is python install related, I will close this ticket, I can't ask you to support my system problems.
