### ISSUE TITLE
Failed to start, python file error 

### ISSUE THREAD

**Issue by AlloyFox** [sezanzeb/input-remapper#466]
```
❯ input-remapper-gtk -d
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 28, in <module>
    from inputremapper.gui.gettext import _, LOCALE_DIR
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/gettext.py", line 24, in <module>
    from inputremapper.configs.data import get_data_path
  File "/usr/lib/python3.10/site-packages/inputremapper/configs/data.py", line 30, in <module>
    from inputremapper.logger import logger
  File "/usr/lib/python3.10/site-packages/inputremapper/logger.py", line 214, in <module>
    VERSION = pkg_resources.require("input-remapper")[0].version
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (typing-extensions 3.10.0.2 (/home/aloy/.local/lib/python3.10/site-packages), Requirement.parse('typing-extensions>=4.1.0'), {'pydantic'})
```

This is what the terminal shows me when I open the program from the terminal, can anyone help me?
I don't have much experience in Linux :(

**Comment by sezanzeb** [comment]
```
VERSION = pkg_resources.require("input-remapper")[0].version
```

errors in this line are not critical at all, I'll change the exception handler to catch all errors

**Comment by jonasBoss** [comment]
It seem like your typing-extensions package is not up to date, which is needed by `python-pydantic`. Also it seems to be installed in your home directory which suggests it was installed with pip. 

Can you install `python-typing-extensions` with your package manager, and then uninstall `typing-extensions` with pip (`$pip uninstall typing-extensions` don't use sudo here).
