### ISSUE TITLE
Griffin Powermate

### ISSUE THREAD

**Issue by bennypowers** [sezanzeb/input-remapper#554]
Howdy! My old powermate usb shows up in the list, and I was able to remap the button to mute - cool! What would it take to get input-remapper to also remap the knob turning?

Thanks for publishing this package!

**Comment by jonasBoss** [comment]
can you try the beta branch? Most likely it will work on beta already.

**Comment by bennypowers** [comment]
New UI looks great!

I was not able to record button0 or knob turns for the powermate using the record button, This was also the case with my Logitech MX Ergo Multi-Device Trackball - the record ui button seemed to have no effect. This was also the case with my cantor keyboard

**Comment by bennypowers** [comment]
<details><summary>Error for the trackball, when I press `Apply`:</summary>

```
Nov 22 17:07:59 i input-remapper.desktop[6217]: Loaded config from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/config.json"
Nov 22 17:07:59 i input-remapper.desktop[6217]: Request to start injecting for "Logitech MX Ergo Multi-Device Trackball "
Nov 22 17:07:59 i input-remapper.desktop[6217]: Found "Griffin PowerMate", "input-remapper keyboard", "Logitech MX Ergo Multi-Device Trackball ", "Video Bus", "FT FIDO KB", "Diego Palacios cantor", "Sleep Button"
Nov 22 17:07:59 i input-remapper.desktop[6217]: Loading preset from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/presets/Logitech MX Ergo Multi-Device Trackball /Side Buttons Overview.json"
Nov 22 17:07:59 i input-remapper.desktop[6217]: Stopping injecting keycodes for group "Logitech MX Ergo Multi-Device Trackball "
Nov 22 17:07:59 i input-remapper.desktop[9686]: Starting injecting the preset for "Logitech MX Ergo Multi-Device Trackball "
Nov 22 17:07:59 i kernel: input: input-remapper Logitech MX Ergo Multi-Device Trackball  forwarded as /devices/virtual/input/input30
Nov 22 17:07:59 i input-remapper.desktop[9686]: Process Logitech MX Ergo Multi-Device Trackball :
Nov 22 17:07:59 i input-remapper.desktop[9686]: Traceback (most recent call last):
Nov 22 17:07:59 i input-remapper.desktop[9686]:   File "/usr/lib64/python3.11/multiprocessing/process.py", line 314, in _bootstrap
Nov 22 17:07:59 i input-remapper.desktop[9686]:     self.run()
Nov 22 17:07:59 i input-remapper.desktop[9686]:   File "/usr/local/lib/python3.11/site-packages/inputremapper/injection/injector.py", line 392, in run
Nov 22 17:07:59 i input-remapper.desktop[9686]:     loop.run_until_complete(asyncio.gather(*coroutines))
Nov 22 17:07:59 i input-remapper.desktop[9686]:   File "/usr/lib64/python3.11/asyncio/base_events.py", line 650, in run_until_complete
Nov 22 17:07:59 i input-remapper.desktop[9686]:     return future.result()
Nov 22 17:07:59 i input-remapper.desktop[9686]:            ^^^^^^^^^^^^^^^
Nov 22 17:07:59 i input-remapper.desktop[9686]:   File "/usr/local/lib/python3.11/site-packages/inputremapper/injection/event_reader.py", line 193, in run
Nov 22 17:07:59 i input-remapper.desktop[9686]:     async for event in self.read_loop():
Nov 22 17:07:59 i input-remapper.desktop[9686]:   File "/usr/local/lib/python3.11/site-packages/inputremapper/injection/event_reader.py", line 90, in read_loop
Nov 22 17:07:59 i input-remapper.desktop[9686]:     _, pending = await asyncio.wait(
Nov 22 17:07:59 i input-remapper.desktop[9686]:                  ^^^^^^^^^^^^^^^^^^^
Nov 22 17:07:59 i input-remapper.desktop[9686]:   File "/usr/lib64/python3.11/asyncio/tasks.py", line 415, in wait
Nov 22 17:07:59 i input-remapper.desktop[9686]:     raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
Nov 22 17:07:59 i input-remapper.desktop[9686]: TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

</details>

<details><summary>Error for the powermate, when I press `Apply`:</summary>

```
Nov 22 17:09:23 i input-remapper.desktop[6217]: Loaded config from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/config.json"
Nov 22 17:09:23 i input-remapper.desktop[6217]: Request to start injecting for "Griffin PowerMate"
Nov 22 17:09:23 i input-remapper.desktop[6217]: Loading preset from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/presets/Griffin PowerMate/Default.json"
Nov 22 17:09:23 i input-remapper.desktop[6217]: Stopping injecting keycodes for group "Griffin PowerMate"
Nov 22 17:09:23 i input-remapper.desktop[9810]: Starting injecting the preset for "Griffin PowerMate"
Nov 22 17:09:23 i kernel: input: input-remapper Griffin PowerMate forwarded as /devices/virtual/input/input32
Nov 22 17:09:23 i input-remapper.desktop[9810]: Process Griffin PowerMate:
Nov 22 17:09:23 i input-remapper.desktop[9810]: Traceback (most recent call last):
Nov 22 17:09:23 i input-remapper.desktop[9810]:   File "/usr/lib64/python3.11/multiprocessing/process.py", line 314, in _bootstrap
Nov 22 17:09:23 i input-remapper.desktop[9810]:     self.run()
Nov 22 17:09:23 i input-remapper.desktop[9810]:   File "/usr/local/lib/python3.11/site-packages/inputremapper/injection/injector.py", line 392, in run
Nov 22 17:09:23 i input-remapper.desktop[9810]:     loop.run_until_complete(asyncio.gather(*coroutines))
Nov 22 17:09:23 i input-remapper.desktop[9810]:   File "/usr/lib64/python3.11/asyncio/base_events.py", line 650, in run_until_complete
Nov 22 17:09:23 i input-remapper.desktop[9810]:     return future.result()
Nov 22 17:09:23 i input-remapper.desktop[9810]:            ^^^^^^^^^^^^^^^
Nov 22 17:09:23 i input-remapper.desktop[9810]:   File "/usr/local/lib/python3.11/site-packages/inputremapper/injection/event_reader.py", line 193, in run
Nov 22 17:09:23 i input-remapper.desktop[9810]:     async for event in self.read_loop():
Nov 22 17:09:23 i input-remapper.desktop[9810]:   File "/usr/local/lib/python3.11/site-packages/inputremapper/injection/event_reader.py", line 90, in read_loop
Nov 22 17:09:23 i input-remapper.desktop[9810]:     _, pending = await asyncio.wait(
Nov 22 17:09:23 i input-remapper.desktop[9810]:                  ^^^^^^^^^^^^^^^^^^^
Nov 22 17:09:23 i input-remapper.desktop[9810]:   File "/usr/lib64/python3.11/asyncio/tasks.py", line 415, in wait
Nov 22 17:09:23 i input-remapper.desktop[9810]:     raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
Nov 22 17:09:23 i input-remapper.desktop[9810]: TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

</details>

**Comment by jonasBoss** [comment]
I wonder if this is an issue with python 3.11, I have never seen it crash there with older python versions. And I guess no one tested 3.11 yet.

**Comment by jonasBoss** [comment]
according to the python [doc](https://docs.python.org/3/library/asyncio-task.html#waiting-primitives):
> Changed in version 3.11: Passing coroutine objects to wait() directly is forbidden.

can you test this branch instead: https://github.com/jonasBoss/key-mapper/tree/python311

**Comment by bennypowers** [comment]
I tried these steps:
```
sudo pip uninstall input-remapper
sudo pip install --no-binary :all: git+https://github.com/jonasBoss/key-mapper.git@python311
journalctl -f
```

Then I launched input-remapper from gnome shell and tried to apply the presets for the trackball and for the powermate. This was the output:

<details><summary>journalctl output</summary>

```
Nov 23 07:15:04 i input-remapper.desktop[25005]: Found "Griffin PowerMate"
Nov 23 07:15:04 i input-remapper.desktop[25005]: Loading group "Griffin PowerMate"
Nov 23 07:15:04 i input-remapper.desktop[25005]: Loading preset "Default"
Nov 23 07:15:04 i input-remapper.desktop[25005]: Loading preset from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/presets/Griffin PowerMate/Default.json"
Nov 23 07:15:04 i input-remapper.desktop[25041]: Found "Logitech MX Ergo Multi-Device Trackball ", "Griffin PowerMate", "input-remapper keyboard", "Video Bus", "FT FIDO KB", "Diego Palacios cantor", "Sleep Button"
Nov 23 07:15:08 i gnome-character[24885]: JS LOG: Characters Application exiting
Nov 23 07:15:11 i input-remapper.desktop[25005]: Loading group "Logitech MX Ergo Multi-Device Trackball "
Nov 23 07:15:11 i input-remapper.desktop[25005]: Loading preset "Side Buttons Overview"
Nov 23 07:15:11 i input-remapper.desktop[25005]: Loading preset from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/presets/Logitech MX Ergo Multi-Device Trackball /Side Buttons Overview.json"
Nov 23 07:15:12 i input-remapper.desktop[25005]: Loading preset "Side Buttons Overview"
Nov 23 07:15:12 i input-remapper.desktop[25005]: Loading preset from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/presets/Logitech MX Ergo Multi-Device Trackball /Side Buttons Overview.json"
Nov 23 07:15:15 i input-remapper.desktop[6217]: Loaded config from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/config.json"
Nov 23 07:15:15 i input-remapper.desktop[6217]: Request to start injecting for "Logitech MX Ergo Multi-Device Trackball "
Nov 23 07:15:15 i input-remapper.desktop[6217]: Found "Logitech MX Ergo Multi-Device Trackball ", "Griffin PowerMate", "input-remapper keyboard", "Video Bus", "FT FIDO KB", "Diego Palacios cantor", "Sleep Button"
Nov 23 07:15:15 i input-remapper.desktop[6217]: Loading preset from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/presets/Logitech MX Ergo Multi-Device Trackball /Side Buttons Overview.json"
Nov 23 07:15:15 i input-remapper.desktop[6217]: Stopping injecting keycodes for group "Logitech MX Ergo Multi-Device Trackball "
Nov 23 07:15:15 i input-remapper.desktop[25071]: Starting injecting the preset for "Logitech MX Ergo Multi-Device Trackball "
Nov 23 07:15:15 i kernel: input: input-remapper Logitech MX Ergo Multi-Device Trackball  forwarded as /devices/virtual/input/input45
Nov 23 07:15:15 i input-remapper.desktop[25071]: Process Logitech MX Ergo Multi-Device Trackball :
Nov 23 07:15:15 i input-remapper.desktop[25071]: Traceback (most recent call last):
Nov 23 07:15:15 i input-remapper.desktop[25071]:   File "/usr/lib64/python3.11/multiprocessing/process.py", line 314, in _bootstrap
Nov 23 07:15:15 i input-remapper.desktop[25071]:     self.run()
Nov 23 07:15:15 i input-remapper.desktop[25071]:   File "/usr/local/lib/python3.11/site-packages/inputremapper/injection/injector.py", line 392, in run
Nov 23 07:15:15 i input-remapper.desktop[25071]:     loop.run_until_complete(asyncio.gather(*coroutines))
Nov 23 07:15:15 i input-remapper.desktop[25071]:   File "/usr/lib64/python3.11/asyncio/base_events.py", line 650, in run_until_complete
Nov 23 07:15:15 i input-remapper.desktop[25071]:     return future.result()
Nov 23 07:15:15 i input-remapper.desktop[25071]:            ^^^^^^^^^^^^^^^
Nov 23 07:15:15 i input-remapper.desktop[25071]:   File "/usr/local/lib/python3.11/site-packages/inputremapper/injection/event_reader.py", line 193, in run
Nov 23 07:15:15 i input-remapper.desktop[25071]:     async for event in self.read_loop():
Nov 23 07:15:15 i input-remapper.desktop[25071]:   File "/usr/local/lib/python3.11/site-packages/inputremapper/injection/event_reader.py", line 90, in read_loop
Nov 23 07:15:15 i input-remapper.desktop[25071]:     _, pending = await asyncio.wait(
Nov 23 07:15:15 i input-remapper.desktop[25071]:                  ^^^^^^^^^^^^^^^^^^^
Nov 23 07:15:15 i input-remapper.desktop[25071]:   File "/usr/lib64/python3.11/asyncio/tasks.py", line 415, in wait
Nov 23 07:15:15 i input-remapper.desktop[25071]:     raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
Nov 23 07:15:15 i input-remapper.desktop[25071]: TypeError: Passing coroutines is forbidden, use tasks explicitly.
Nov 23 07:15:15 i input-remapper.desktop[6217]: ERROR: Injector was unexpectedly found stopped
Nov 23 07:15:15 i systemd-udevd[25073]: input45: Process '/bin/input-remapper-control --command autoload --device ' failed with exit code 2.
Nov 23 07:15:16 i systemd-udevd[25075]: event22: Process '/bin/input-remapper-control --command autoload --device /dev/input/event22' failed with exit code 4.
Nov 23 07:15:16 i gnome-shell[3313]: Could not open device /dev/input/event22: Could not get device info for path /dev/input/event22: No such file or directory
Nov 23 07:15:16 i systemd-udevd[25073]: mouse2: Process '/bin/input-remapper-control --command autoload --device /dev/input/mouse2' failed with exit code 4.
Nov 23 07:15:22 i input-remapper.desktop[25005]: Loading group "Griffin PowerMate"
Nov 23 07:15:22 i input-remapper.desktop[25005]: Loading preset "Default"
Nov 23 07:15:22 i input-remapper.desktop[25005]: Loading preset from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/presets/Griffin PowerMate/Default.json"
Nov 23 07:15:23 i input-remapper.desktop[25005]: Loading preset "Default"
Nov 23 07:15:23 i input-remapper.desktop[25005]: Loading preset from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/presets/Griffin PowerMate/Default.json"
Nov 23 07:15:24 i input-remapper.desktop[6217]: Loaded config from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/config.json"
Nov 23 07:15:24 i input-remapper.desktop[6217]: Request to start injecting for "Griffin PowerMate"
Nov 23 07:15:24 i input-remapper.desktop[6217]: Loading preset from "/home/bennyp/.config/input-remapper/beta_1.6.0-beta/presets/Griffin PowerMate/Default.json"
Nov 23 07:15:24 i input-remapper.desktop[6217]: Stopping injecting keycodes for group "Griffin PowerMate"
Nov 23 07:15:24 i input-remapper.desktop[25093]: Starting injecting the preset for "Griffin PowerMate"
Nov 23 07:15:24 i kernel: input: input-remapper Griffin PowerMate forwarded as /devices/virtual/input/input46
Nov 23 07:15:24 i input-remapper.desktop[25093]: Process Griffin PowerMate:
Nov 23 07:15:24 i input-remapper.desktop[25093]: Traceback (most recent call last):
Nov 23 07:15:24 i input-remapper.desktop[25093]:   File "/usr/lib64/python3.11/multiprocessing/process.py", line 314, in _bootstrap
Nov 23 07:15:24 i input-remapper.desktop[25093]:     self.run()
Nov 23 07:15:24 i input-remapper.desktop[25093]:   File "/usr/local/lib/python3.11/site-packages/inputremapper/injection/injector.py", line 392, in run
Nov 23 07:15:24 i input-remapper.desktop[25093]:     loop.run_until_complete(asyncio.gather(*coroutines))
Nov 23 07:15:24 i input-remapper.desktop[25093]:   File "/usr/lib64/python3.11/asyncio/base_events.py", line 650, in run_until_complete
Nov 23 07:15:24 i input-remapper.desktop[25093]:     return future.result()
Nov 23 07:15:24 i input-remapper.desktop[25093]:            ^^^^^^^^^^^^^^^
Nov 23 07:15:24 i input-remapper.desktop[25093]:   File "/usr/local/lib/python3.11/site-packages/inputremapper/injection/event_reader.py", line 193, in run
Nov 23 07:15:24 i input-remapper.desktop[25093]:     async for event in self.read_loop():
Nov 23 07:15:24 i input-remapper.desktop[25093]:   File "/usr/local/lib/python3.11/site-packages/inputremapper/injection/event_reader.py", line 90, in read_loop
Nov 23 07:15:24 i input-remapper.desktop[25093]:     _, pending = await asyncio.wait(
Nov 23 07:15:24 i input-remapper.desktop[25093]:                  ^^^^^^^^^^^^^^^^^^^
Nov 23 07:15:24 i input-remapper.desktop[25093]:   File "/usr/lib64/python3.11/asyncio/tasks.py", line 415, in wait
Nov 23 07:15:24 i input-remapper.desktop[25093]:     raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
Nov 23 07:15:24 i input-remapper.desktop[25093]: TypeError: Passing coroutines is forbidden, use tasks explicitly.
Nov 23 07:15:24 i input-remapper.desktop[6217]: ERROR: Injector was unexpectedly found stopped
Nov 23 07:15:24 i systemd-udevd[25095]: input46: Process '/bin/input-remapper-control --command autoload --device ' failed with exit code 2.
Nov 23 07:15:25 i systemd-udevd[25095]: event22: Process '/bin/input-remapper-control --command autoload --device /dev/input/event22' failed with exit code
```

</details>

**Comment by bennypowers** [comment]
Now it's working, presumably since i logged out or rebooted. Nice!

**Comment by sezanzeb** [comment]
> New UI looks great!

Thank you!
