### ISSUE TITLE
Ubuntu 20.04.6, record doesn't work

### ISSUE THREAD

**Issue by henry1992007** [sezanzeb/input-remapper#676]
when I hit record and type my keyboard, nothing happened, and the log seem to show something error.

10:00:04.761744 5032 reader-service DEBUG reader_service.py:195: Received command "Logitech USB Keyboard"
10:00:04.763872 5032 reader-service DEBUG event_reader.py:190: Starting to listen for events from /dev/input/event6, fd 17
10:00:04.763978 5032 reader-service DEBUG event_reader.py:190: Starting to listen for events from /dev/input/event5, fd 18
10:00:04.764035 5032 reader-service DEBUG event_reader.py:190: Starting to listen for events from /dev/input/event4, fd 19
10:00:04.764187 5032 reader-service DEBUG event_reader.py:108: read loop stopped
Task exception was never retrieved
future: <Task finished name='Task-25' coro=<Event.wait() done, defined at /usr/lib/python3.8/asyncio/locks.py:296> exception=RuntimeError("Task <Task pending name='Task-25' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-25' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop
10:00:04.764313 5032 reader-service INFO event_reader.py:206: read loop for /dev/input/event6 stopped
10:00:04.795484 5032 reader-service DEBUG event_reader.py:108: read loop stopped
Task exception was never retrieved
future: <Task finished name='Task-27' coro=<Event.wait() done, defined at /usr/lib/python3.8/asyncio/locks.py:296> exception=RuntimeError("Task <Task pending name='Task-27' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-27' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop
10:00:04.795738 5032 reader-service INFO event_reader.py:206: read loop for /dev/input/event5 stopped
10:00:04.827340 5032 reader-service DEBUG event_reader.py:108: read loop stopped
Task exception was never retrieved
future: <Task finished name='Task-29' coro=<Event.wait() done, defined at /usr/lib/python3.8/asyncio/locks.py:296> exception=RuntimeError("Task <Task pending name='Task-29' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-29' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop
10:00:04.827737 5032 reader-service INFO event_reader.py:206: read loop for /dev/input/event4 stopped

**Comment by IanBand** [comment]
getting the same error on 20.04.4

downgrading to 1.5.1 worked for me in the meantime

**Comment by mickeyl** [comment]
https://stackoverflow.com/questions/53724665/using-queues-results-in-asyncio-exception-got-future-future-pending-attached might be helpful.

I wonder why not all people are getting this. Is this perhaps working differently on older/newer python runtimes?

**Comment by sezanzeb** [comment]
All of you were using 3.8, maybe

**Comment by jonasBoss** [comment]
python 3.8 looks like a good observation. #704 also uses 3.8 with a similar issue

**Comment by mickeyl** [comment]
Which version are the people running for whom it works?

**Comment by jonasBoss** [comment]
Newer python versions seem to work. I am on python 3.10 and there are people with 3.11

**Comment by sezanzeb** [comment]
I'm using python 3.10 as well

**Comment by sezanzeb** [comment]
3.10 is available in ubuntu 22.04: https://packages.ubuntu.com/search?keywords=python+3.10&searchon=names

**Comment by rome-legacy** [comment]
I have the same issue on ubuntu 20.04 with python 3.8.
i have installed python3.11 but having issues running it as my main python version. Is there a possibility to use this version only for input-remapper?

**Comment by sezanzeb** [comment]
> Is there a possibility to use this version only for input-remapper?

Probably not. I'll close this issue now
