### ISSUE TITLE
2.0.0 fails on OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by KayTaneJupiter** [sezanzeb/input-remapper#682]
# systemctl restart input-remapper

```
Job for input-remapper.service failed because the control process exited with error code.
See "systemctl status input-remapper.service" and "journalctl -xeu input-remapper.service" for details.
```

```
input-remapper-service[17702]: Traceback (most recent call last):
input-remapper-service[17702]:   File "/usr/bin/input-remapper-service", line 47, in <module>
input-remapper-service[17702]:     from inputremapper.daemon import Daemon
input-remapper-service[17702]:   File "/usr/lib/python3.10/site-packages/inputremapper/daemon.py", line 42, in <module>
input-remapper-service[17702]:     from inputremapper.injection.injector import Injector, InjectorState
input-remapper-service[17702]:   File "/usr/lib/python3.10/site-packages/inputremapper/injection/injector.py", line 36, in <module>
input-remapper-service[17702]:     from inputremapper.configs.input_config import InputCombination, InputConfig, DeviceHash
input-remapper-service[17702]:   File "/usr/lib/python3.10/site-packages/inputremapper/configs/input_config.py", line 31, in <module>
input-remapper-service[17702]:     from inputremapper.gui.messages.message_types import MessageType
input-remapper-service[17702]:   File "/usr/lib/python3.10/site-packages/inputremapper/gui/__init__.py", line 6, in <module>
input-remapper-service[17702]:     gi.require_version("GtkSource", "4")
input-remapper-service[17702]:   File "/usr/lib64/python3.10/site-packages/gi/__init__.py", line 126, in require_version
input-remapper-service[17702]:     raise ValueError('Namespace %s not available' % namespace)
input-remapper-service[17702]: ValueError: Namespace GtkSource not available
```

**Comment by M-Paulsen** [comment]
Hi, did you ever find a solution for this?

**Comment by KayTaneJupiter** [comment]
> Hi, did you ever find a solution for this?

I have not tried anything with it since that post.

**Comment by jonasBoss** [comment]
looks like a missing dependency: `gtksourceview4`

**Comment by wyatt-herkamp** [comment]
As a note to anyone who might be having issues installing on Opensuse tumbleweed
#### System Info
![image](https://github.com/sezanzeb/input-remapper/assets/11785959/1964457e-967e-4721-9aa3-271960df354b)

I had a few other issues installing this on OpenSuse

This is how I did it

```bash
# Regular Depends
sudo zypper install typelib-1_0-GtkSource-4 typelib-1_0-Gtk-4_0 gobject-introspection-devel gtksourceview4 cairo-devel
# Python Related Depends - you might have to change to python312 in the future. 
sudo zypper install python311-devel python311-pydbus  python3-pydantic python311-evdev
```

Then it would not let me use `pip` or `pipx`

So I ran 
```bash
git clone https://github.com/sezanzeb/input-remapper.git
cd input-remapper

python3 ./setup.py build
sudo python3 ./setup.py install
```
##### Note
The `setup.py` has a deprecation notice but using pip was not working. 

After that you just need to enable the service

```bash
sudo systemctl enable input-remapper
sudo systemctl restart input-remapper
```

Hopefully that helps anyone who needs help in the future.
