### ISSUE TITLE
2.0 doesn't work anymore

### ISSUE THREAD

**Issue by mickeyl** [sezanzeb/input-remapper#697]
Upgraded from 1.4 and then all the mappings stopped worked. Rebooted and made sure that the daemon is running. The presets are still visible in the GUI. How can I help debugging this?

**Comment by sezanzeb** [comment]
Are errors visible on the bottom of the gui when you open the mapping?

Like this:

![image](https://user-images.githubusercontent.com/28510156/236608457-d1ac04be-d99d-4d39-b517-fcebbd0248a1.png)

**Comment by sezanzeb** [comment]
Have you checked in the gui if the presets are complete?

**Comment by leysont** [comment]
It also stopped working for me since the update. I see no error messages.

> Have you checked in the gui if the presets are complete?

What exactly do you mean by complete?

**Comment by sezanzeb** [comment]
For example, if you mapped "a" to "b" before the upgrade, is "a" still mapped to "b" now according to the gui?

> and then all the mappings stopped worked

What exactly is not working? This is too vague. Is autoload not working anymore? Is it not doing anything when hitting the "apply" button?

**Comment by leysont** [comment]
I got it to work again. I had to remake my preset for some reason. The old one just doesn't work, neither with autoload nor with apply. There are no errors, either.

**Comment by mickeyl** [comment]
Not here. I can't even get it to record keystrokes: Here's some debug output:

```
10:29:54.373508 11296 reader-service DEBUG reader_service.py:195: Received command "Microsoft Microsoft® Nano Transceiver v2.1"
10:29:54.374507 11296 reader-service DEBUG system_mapping.py:128: Gathering available keycodes
10:29:54.379820 11296 reader-service DEBUG system_mapping.py:114: Writing "/home/mickey/.config/input-remapper-2/xmodmap.json"
10:29:54.380487 11296 reader-service DEBUG system_mapping.py:128: Gathering available keycodes
10:29:54.387255 11296 reader-service DEBUG system_mapping.py:114: Writing "/home/mickey/.config/input-remapper-2/xmodmap.json"
10:29:54.396731 11296 reader-service DEBUG event_reader.py:190: Starting to listen for events from /dev/input/event9, fd 17
10:29:54.397001 11296 reader-service DEBUG event_reader.py:190: Starting to listen for events from /dev/input/event8, fd 18
10:29:54.397113 11296 reader-service DEBUG event_reader.py:190: Starting to listen for events from /dev/input/event6, fd 19
10:29:54.397189 11296 reader-service DEBUG event_reader.py:190: Starting to listen for events from /dev/input/event5, fd 20
10:29:54.397435 11296 reader-service DEBUG event_reader.py:108: read loop stopped
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Event.wait() done, defined at /usr/lib/python3.8/asyncio/locks.py:296> exception=RuntimeError("Task <Task pending name='Task-8' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-8' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop
10:29:54.397812 11296 reader-service INFO event_reader.py:206: read loop for /dev/input/event9 stopped
10:29:54.429179 11296 reader-service DEBUG event_reader.py:108: read loop stopped
Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Event.wait() done, defined at /usr/lib/python3.8/asyncio/locks.py:296> exception=RuntimeError("Task <Task pending name='Task-10' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-10' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop
10:29:54.429779 11296 reader-service INFO event_reader.py:206: read loop for /dev/input/event8 stopped
10:29:54.449257 11296 reader-service DEBUG event_reader.py:108: read loop stopped
Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Event.wait() done, defined at /usr/lib/python3.8/asyncio/locks.py:296> exception=RuntimeError("Task <Task pending name='Task-12' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-12' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop
10:29:54.449800 11296 reader-service INFO event_reader.py:206: read loop for /dev/input/event6 stopped
10:29:54.481216 11296 reader-service DEBUG event_reader.py:108: read loop stopped
Task exception was never retrieved
future: <Task finished name='Task-14' coro=<Event.wait() done, defined at /usr/lib/python3.8/asyncio/locks.py:296> exception=RuntimeError("Task <Task pending name='Task-14' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-14' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.8/asyncio/tasks.py:518]> got Future <Future pending> attached to a different loop
10:29:54.481805 11296 reader-service INFO event_reader.py:206: read loop for /dev/input/event5 stopped
```

Does that ring a bell?

**Comment by sezanzeb** [comment]
This apparently affects multiple people https://github.com/sezanzeb/input-remapper/issues/676 https://github.com/sezanzeb/input-remapper/issues/429

**Comment by mickeyl** [comment]
Ok, no need to keep the duplicate then. Closing this here.
