### ISSUE TITLE
press start not working. The service isn't starting.

### ISSUE THREAD

**Issue by antonio24073** [sezanzeb/input-remapper#714]
Hi 

I changed my m.2 from another computer and it stopped to work in the new computer. 
I isn't able to reset (purge) the application. I tried to delete the folder `~/.config/input-remapper-2`
I press start and it isn't working. The service isn't starting too.

Thank you for the plugin. 

Best regards,

0 - Please install the newest version from source to see if the problem has already been solved.

```
I reinstalled with pamac
```

1. input-remapper-control --version

```
input-remapper 2.0.0 7a0ccac5d5e9609d2b0a1d60c61ec30edc539674 https://github.com/sezanzeb/input-remapper
python-evdev 1.6.1
```

2- which linux distro (ubuntu 20.04, manjaro, etc.)

```
Manjaro Linux
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=22.1.2
DISTRIB_CODENAME=Talos
DISTRIB_DESCRIPTION="Manjaro Linux"
Manjaro Linux
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
```

3- `echo $XDG_SESSION_TYPE`

```
x11
```

4- which desktop environment (gnome, plasma, xfce4, etc.)

```
gnome-shell --version
GNOME Shell 43.5
```

5- `sudo ls -l /proc/1/exe`

```
lrwxrwxrwx 1 root root 0 May 24 23:53 /proc/1/exe -> /usr/lib/systemd/systemd
```

6. paste the affected preset .json file from ~/.config/input-remapper-2/presets

```
cat  ~/.config/input-remapper-2/presets/USB\ USB\ Keykoard/SHIFT.json  
[
    {
        "input_combination": [
            {
                "type": 1,
                "code": 155,
                "origin_hash": "12bd8ac955ac720a477b924a58e14eee"
            }
        ],
        "target_uinput": "keyboard",
        "output_symbol": "Shift_R",
        "mapping_type": "key_macro"
    }
]
```

9. `sudo pkill -f input-remapper-service && input-remapper-gtk -d`, apply the preset and hit your key. Then share that log.

```
01:15:16.157740 161229 GUI DEBUG logger.py:297: Using rich.traceback
01:15:16.157944 161229 GUI INFO logger.py:265: input-remapper-gtk 2.0.0 7a0ccac5d5e9609d2b0a1d60c61ec30edc539674 https://github.com/sezanzeb/input-remapper
01:15:16.158135 161229 GUI INFO logger.py:273: python-evdev 1.6.1
01:15:16.158276 161229 GUI WARNING logger.py:276: Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
01:15:16.158390 161229 GUI DEBUG input-remapper-gtk:67: Using locale directory: /usr/share/input-remapper/lang
01:15:16.181733 161229 GUI DEBUG pipe.py:87: Using existing pipe for "/tmp/input-remapper-antonio/reader-results"
01:15:16.182022 161229 GUI DEBUG pipe.py:87: Using existing pipe for "/tmp/input-remapper-antonio/reader-commands"
01:15:16.182279 161229 GUI DEBUG message_broker.py:97: adding new Listener for MessageType.terminate: <function ReaderClient.attach_to_events.<locals>.<lambda> at 0x7f1c26577370>
01:15:16.183162 161229 GUI DEBUG reader_service.py:144: Running `pkexec input-remapper-control --command start-reader-service -d`
01:15:20.591520 161265 control DEBUG input-remapper-control:233: Call for "['/usr/bin/input-remapper-control', '--command', 'start-reader-service', '-d']"
01:15:20.607785 161265 control DEBUG input-remapper-control:215: System is booted
01:15:20.608046 161265 control DEBUG input-remapper-control:178: Running `input-remapper-reader-service -d &`
01:15:20.613612 161265 control INFO input-remapper-control:263: Done
01:15:20.670839 161229 GUI INFO daemon.py:234: Starting the service
01:15:20.671135 161229 GUI DEBUG daemon.py:245: Running `pkexec input-remapper-control --command start-daemon  -d`
01:15:21.231920 161388 reader-service DEBUG data.py:96: Found data at "/usr/share/input-remapper"
01:15:21.261797 161388 reader-service DEBUG pipe.py:87: Using existing pipe for "/tmp/input-remapper-antonio/reader-results"
01:15:21.262262 161388 reader-service DEBUG pipe.py:87: Using existing pipe for "/tmp/input-remapper-antonio/reader-commands"
01:15:21.263048 161388 reader-service DEBUG reader_service.py:154: Discovering initial groups
01:15:21.263895 161388 reader-service DEBUG groups.py:354: Discovering device paths
01:15:21.304751 161388 reader-service DEBUG groups.py:391: "HDA Intel PCH Front Headphone" has no useful capabilities
01:15:21.357472 161393 control DEBUG input-remapper-control:233: Call for "['/usr/bin/input-remapper-control', '--command', 'start-daemon', '-d']"
01:15:21.371901 161393 control DEBUG input-remapper-control:215: System is booted
01:15:21.372124 161393 control DEBUG input-remapper-control:178: Running `input-remapper-service --hide-info -d &`
01:15:21.377865 161393 control INFO input-remapper-control:263: Done
01:15:21.381549 161388 reader-service DEBUG groups.py:391: "HDA Intel PCH Line Out CLFE" has no useful capabilities
01:15:21.444880 161388 reader-service DEBUG groups.py:391: "HDA Intel PCH Line Out Surround" has no useful capabilities
01:15:21.514877 161388 reader-service DEBUG groups.py:391: "HDA Intel PCH Line Out Front" has no useful capabilities
01:15:21.574833 161388 reader-service DEBUG groups.py:391: "HDA Intel PCH Line" has no useful capabilities
01:15:21.631589 161388 reader-service DEBUG groups.py:391: "HDA Intel PCH Rear Mic" has no useful capabilities
01:15:21.632983 161229 GUI DEBUG daemon.py:255: Attempt 1 to reach the service failed:
01:15:21.633219 161229 GUI DEBUG daemon.py:256: "g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name inputremapper.Control was not provided by any .service files (2)"
01:15:21.701561 161388 reader-service DEBUG groups.py:391: "HDA Intel PCH Front Mic" has no useful capabilities
01:15:21.774879 161388 reader-service DEBUG groups.py:391: "HDA ATI HDMI HDMI/DP,pcm=7" has no useful capabilities
01:15:21.834893 161229 GUI DEBUG daemon.py:255: Attempt 2 to reach the service failed:
01:15:21.835092 161229 GUI DEBUG daemon.py:256: "g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name inputremapper.Control was not provided by any .service files (2)"
01:15:21.838200 161388 reader-service DEBUG groups.py:391: "HDA ATI HDMI HDMI/DP,pcm=3" has no useful capabilities
01:15:21.901553 161388 reader-service DEBUG groups.py:391: "PC Speaker" has no useful capabilities
01:15:21.955604 161388 reader-service DEBUG groups.py:402: Found mouse "USB OPTICAL MOUSE " at "/dev/input/event5", hash "3589c41b9dbe096fe526f8810994c801", key "3_10077_2982_usb-0000:00:1a.0-1.4"
01:15:21.984949 161388 reader-service DEBUG groups.py:402: Found unknown "USB USB Keykoard System Control" at "/dev/input/event4", hash "a5915112d949e8078a638c6da110a685", key "3_7247_2_usb-0000:00:1d.0-1.2"
01:15:22.015338 161388 reader-service DEBUG groups.py:402: Found unknown "USB USB Keykoard Consumer Control" at "/dev/input/event3", hash "12bd8ac955ac720a477b924a58e14eee", key "3_7247_2_usb-0000:00:1d.0-1.2"
01:15:22.036738 161229 GUI DEBUG daemon.py:255: Attempt 3 to reach the service failed:
01:15:22.036955 161229 GUI DEBUG daemon.py:256: "g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name inputremapper.Control was not provided by any .service files (2)"
01:15:22.048656 161388 reader-service DEBUG groups.py:402: Found keyboard "USB USB Keykoard" at "/dev/input/event2", hash "219a6cbe86793d1654b63862ca254d85", key "3_7247_2_usb-0000:00:1d.0-1.2"
01:15:22.064649 161411 service DEBUG data.py:96: Found data at "/usr/share/input-remapper"
01:15:22.101398 161411 service DEBUG daemon.py:196: Creating daemon
01:15:22.101882 161411 service INFO global_config.py:109: Loaded config from "/home/antonio/.config/input-remapper-2/config.json"
01:15:22.102058 161411 service DEBUG shared_dict.py:57: Starting SharedDict process
01:15:22.107196 161429 service DEBUG shared_dict.py:63: SharedDict process started
01:15:22.118881 161388 reader-service INFO groups.py:481: Found "USB OPTICAL MOUSE ", "USB USB Keykoard"
01:15:22.119223 161388 reader-service DEBUG reader_service.py:161: Sending groups
01:15:22.120111 161411 service DEBUG daemon.py:281: Running daemon
01:15:22.120179 161388 reader-service DEBUG reader_service.py:193: Waiting for commands
01:15:22.237506 161229 GUI ERROR daemon.py:259: Failed to connect to the service
```

11. `sudo evtest` while the previous command is running, to see how events are injected. Devices starting with `input-remapper ...` are of interest.
--> previous command did not block the command line

12 - sudo systemctl restart input-remapper

```
Job for input-remapper.service failed because the control process exited with error code.
See "systemctl status input-remapper.service" and "journalctl -xeu input-remapper.service" for details.
```

13 - journalctl -f | grep input-remapper

```
May 25 00:56:47 manjaro input-remapper-gtk.desktop[129573]: input-remapper-gtk 2.0.0 7a0ccac5d5e9609d2b0a1d60c61ec30edc539674 https://github.com/sezanzeb/input-remapper
May 25 00:56:47 manjaro input-remapper-gtk.desktop[129573]: python-evdev 1.6.1
May 25 00:56:53 manjaro polkitd[751]: Operator of unix-session:3 successfully authenticated as unix-user:antonio to gain TEMPORARY authorization for action inputremapper for unix-process:129573:384046 [/usr/bin/python3 /usr/bin/input-remapper-gtk] (owned by unix-user:antonio)
May 25 00:56:53 manjaro pkexec[129639]: antonio: Executing command [USER=root] [TTY=unknown] [CWD=/home/antonio] [COMMAND=/usr/bin/input-remapper-control --command start-reader-service]
May 25 00:56:54 manjaro input-remapper-gtk.desktop[129639]: Done
May 25 00:56:54 manjaro input-remapper-gtk.desktop[129573]: Connected to the service
May 25 00:56:54 manjaro input-remapper-gtk.desktop[77606]: Loaded config from "/home/antonio/.config/input-remapper-2/config.json"
May 25 00:56:54 manjaro input-remapper-gtk.desktop[129573]: Loaded config from "/home/antonio/.config/input-remapper-2/config.json"
May 25 00:56:54 manjaro input-remapper-gtk.desktop[129573]: WARNING: HandlerDisabled entry failed: "nothing connected to <bound method CodeEditor._on_gtk_changed of <inputremapper.gui.components.editor.CodeEditor object at 0x7fb6220d9210>>"
May 25 00:56:54 manjaro input-remapper-gtk.desktop[129573]: WARNING: HandlerDisabled exit failed: "nothing connected to <bound method CodeEditor._on_gtk_changed of <inputremapper.gui.components.editor.CodeEditor object at 0x7fb6220d9210>>"
May 25 00:56:55 manjaro input-remapper-gtk.desktop[129573]: Found "input-remapper USB USB Keykoard Consumer Control forwarded", "input-remapper keyboard", "USB OPTICAL MOUSE ", "USB USB Keykoard"
May 25 00:56:55 manjaro input-remapper-gtk.desktop[129573]: Loading group "USB USB Keykoard"
May 25 00:56:55 manjaro input-remapper-gtk.desktop[129573]: Loading preset "SHIFT"
May 25 00:56:55 manjaro input-remapper-gtk.desktop[129573]: Loading preset from "/home/antonio/.config/input-remapper-2/presets/USB USB Keykoard/SHIFT.json"
May 25 00:56:55 manjaro input-remapper-gtk.desktop[129839]: Found "input-remapper USB USB Keykoard Consumer Control forwarded", "input-remapper keyboard", "USB OPTICAL MOUSE ", "USB USB Keykoard"
May 25 00:57:00 manjaro input-remapper-gtk.desktop[129573]: Loading group "USB USB Keykoard"
May 25 00:57:00 manjaro input-remapper-gtk.desktop[129573]: Loading preset "SHIFT"
May 25 00:57:00 manjaro input-remapper-gtk.desktop[129573]: Loading preset from "/home/antonio/.config/input-remapper-2/presets/USB USB Keykoard/SHIFT.json"
May 25 00:57:01 manjaro input-remapper-gtk.desktop[129573]: Loading preset "SHIFT"
May 25 00:57:01 manjaro input-remapper-gtk.desktop[129573]: Loading preset from "/home/antonio/.config/input-remapper-2/presets/USB USB Keykoard/SHIFT.json"
May 25 00:57:03 manjaro input-remapper-gtk.desktop[129573]: Traceback (most recent call last):
May 25 00:57:03 manjaro input-remapper-gtk.desktop[129573]:   File "/usr/lib/python3.10/site-packages/inputremapper/gui/user_interface.py", line 256, in <lambda>
May 25 00:57:03 manjaro input-remapper-gtk.desktop[129573]:     "clicked", lambda *_: self.controller.start_injecting()
May 25 00:57:03 manjaro input-remapper-gtk.desktop[129573]:   File "/usr/lib/python3.10/site-packages/inputremapper/gui/controller.py", line 627, in start_injecting
May 25 00:57:03 manjaro input-remapper-gtk.desktop[129573]:     if self.data_manager.active_preset.dangerously_mapped_btn_left():
May 25 00:57:03 manjaro input-remapper-gtk.desktop[129573]:   File "/usr/lib/python3.10/site-packages/inputremapper/configs/preset.py", line 239, in dangerously_mapped_btn_left
May 25 00:57:03 manjaro input-remapper-gtk.desktop[129573]:     if (ecodes.EV_KEY, ecodes.BTN_LEFT) not in [
May 25 00:57:03 manjaro input-remapper-gtk.desktop[129573]: NameError: name 'ecodes' is not defined
May 25 00:58:14 manjaro dbus-daemon[748]: [system] Activating via systemd: service name='net.reactivated.Fprint' unit='fprintd.service' requested by ':1.1130' (uid=0 pid=132199 comm="sudo systemctl restart input-remapper")
May 25 00:58:17 manjaro dbus-daemon[748]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.1132' (uid=0 pid=132199 comm="sudo systemctl restart input-remapper")
May 25 00:58:17 manjaro sudo[132199]:  antonio : TTY=pts/5 ; PWD=/home/antonio ; USER=root ; COMMAND=/usr/bin/systemctl restart input-remapper
May 25 00:58:18 manjaro input-remapper-service[132355]: input-remapper-service 2.0.0 7a0ccac5d5e9609d2b0a1d60c61ec30edc539674 https://github.com/sezanzeb/input-remapper
May 25 00:58:18 manjaro input-remapper-service[132355]: python-evdev 1.6.1
May 25 00:58:18 manjaro input-remapper-service[132355]: ERROR: Is the service already running? (name already exists on the bus)
May 25 00:58:18 manjaro input-remapper-service[132355]: Stopping all injections
May 25 00:58:18 manjaro systemd[1]: input-remapper.service: Main process exited, code=exited, status=9/n/a
May 25 00:58:18 manjaro systemd[1]: input-remapper.service: Failed with result 'exit-code'.
May 25 00:58:18 manjaro audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=input-remapper comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
May 25 00:58:18 manjaro kernel: audit: type=1130 audit(1684987098.779:5498): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=input-remapper comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
```

**Comment by sezanzeb** [comment]
Fixed in https://github.com/sezanzeb/input-remapper/pull/720
