### ISSUE TITLE
Error while applying remapping to keyboard after update

### ISSUE THREAD

**Issue by terminal-case** [sezanzeb/input-remapper#717]
I ran into an issue where input-remapper would not start today, so I did some digging and found that manually cloning and makepkg-ing it worked to get it running. After that I got the ecodes issue, which I resolved using the site-packages import fix from another issue. There is one more issue I am encountering however, and that is when I attempt to apply a mapping to my keyboard, I get the following error:

`16:00:16.129840 67267 service DEBUG global_uinputs.py:132: Creating regular UInputs
16:00:16.129898 67267 service DEBUG global_uinputs.py:80: creating UInput device: "input-remapper keyboard"
Exception while handling inputremapper.Control.start_injecting()
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pydbus/registration.py", line 81, in call_method
    result = method(*parameters, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/inputremapper/daemon.py", line 510, in start_injecting
    global_uinputs.prepare_single(mapping.target_uinput)
  File "/usr/lib/python3.11/site-packages/inputremapper/injection/global_uinputs.py", line 166, in prepare_single
    self.devices[name] = self._uinput_factory(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/inputremapper/injection/global_uinputs.py", line 81, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/evdev/uinput.py", line 127, in __init__
    self.fd = _uinput.open(devnode)
              ^^^^^^^^^^^^^^^^^^^^^
OSError: could not open uinput device in write mode
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/user_interface.py", line 256, in <lambda>
    "clicked", lambda *_: self.controller.start_injecting()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/controller.py", line 644, in start_injecting
    if not self.data_manager.start_injecting():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/data_manager.py", line 561, in start_injecting
    if self._daemon.start_injecting(self.active_group.key, self.active_preset.name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydbus/proxy_method.py", line 72, in __call__
    ret = instance._bus.con.call_sync(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: GDBus.Error:unknown.OSError: could not open uinput device in write mode (36)`

**Comment by sezanzeb** [comment]
https://stackoverflow.com/a/48641401/4417769

**Comment by sezanzeb** [comment]
As far as I remember `modprobe uinput` is the usual fix for that. Feel free to reopen the issue if you are still having this problem.
