### ISSUE TITLE
Unable to apply  a preset to my device - NameError: name 'ecodes' is not defined

### ISSUE THREAD

**Issue by ForgeLightGeist** [sezanzeb/input-remapper#721]
The device in question is a Logitech G502 Hero.
Here is the output of input-remapper-gtk -d when I press the "apply" button:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/user_interface.py", line 256, in <lambda>
    "clicked", lambda *_: self.controller.start_injecting()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/controller.py", line 627, in start_injecting
    if self.data_manager.active_preset.dangerously_mapped_btn_left():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/preset.py", line 239, in dangerously_mapped_btn_left
    if (ecodes.EV_KEY, ecodes.BTN_LEFT) not in [
        ^^^^^^
NameError: name 'ecodes' is not defined

**Comment by sezanzeb** [comment]
fixed by https://github.com/sezanzeb/input-remapper/pull/720
