### ISSUE TITLE
pydantic.errors.PydanticUserError

### ISSUE THREAD

**Issue by BillboardsAreAllLearing** [sezanzeb/input-remapper#769]
To help people understand your problems, run `sudo pkill -f input-remapper && input-remapper-gtk -d`, reproduce the problem and then share the output here:
```
Traceback (most recent call last):
  File "/usr/bin/input-remapper-control", line 31, in <module>
    from inputremapper.configs.migrations import migrate
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/migrations.py", line 50, in <module>
    from inputremapper.configs.input_config import InputCombination, InputConfig
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 51, in <module>
    class InputConfig(BaseModel):
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 253, in InputConfig
    @root_validator
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.3/u/root-validator-pre-skip
```

I obtain this error when starting input-remapper-control. I can't use as well ```input-remapper-control -h```. This is built from head on git via this AUR package on Arch Linux, [aur.archlinux.org/packages/input-remapper-git](https://aur.archlinux.org/packages/input-remapper-git).

**Comment by PDXUser** [comment]
I have the same exact error:

```Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 39, in <module>
    from inputremapper.gui.reader_service import ReaderService
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/reader_service.py", line 55, in <module>
    from inputremapper.configs.input_config import InputCombination, InputConfig
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 51, in <module>
    class InputConfig(BaseModel):
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 253, in InputConfig
    @root_validator
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.3/u/root-validator-pre-skip
```

Fresh install as of 2 days ago for Arch after upgrading SSD.

**Comment by 7abc39bd7efb38** [comment]
Same. I'm on Fedora 38
Tried installing using dnf and manually. Same result both times.

`$ sudo input-remapper-gtk
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 39, in <module>
    from inputremapper.gui.reader_service import ReaderService
  File "/usr/local/lib/python3.11/site-packages/inputremapper/gui/reader_service.py", line 55, in <module>
    from inputremapper.configs.input_config import InputCombination, InputConfig
  File "/usr/local/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 51, in <module>
    class InputConfig(BaseModel):
  File "/usr/local/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 253, in InputConfig
    @root_validator
     ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.2/u/root-validator-pre-skip
`

**Comment by M8850** [comment]
same on arch prolly after update

```
[2023-09-16T14:17:39+0200] [ALPM] upgraded python-matplotlib (3.7.2-1 -> 3.7.3-1)
[2023-09-16T21:03:35+0200] [ALPM] upgraded python-contourpy (1.1.0-1 -> 1.1.1-1)
[2023-09-17T05:38:26+0200] [ALPM] upgraded glslang (12.3.1-2 -> 13.0.0-1)
[2023-09-17T05:38:26+0200] [ALPM] upgraded libplacebo (5.264.1-2 -> 5.264.1-3)
[2023-09-17T05:38:26+0200] [ALPM] installed python-annotated-types (0.5.0-1)
[2023-09-17T05:38:26+0200] [ALPM] installed python-pydantic-core (1:2.6.3-1)
[2023-09-17T05:38:27+0200] [ALPM] upgraded python-pydantic (1.10.9-1 -> 2.3.0-1)
[2023-09-17T05:38:27+0200] [ALPM] upgraded python-inflect (7.0.0-1 -> 7.0.0-2)
[2023-09-17T05:38:27+0200] [ALPM] upgraded remmina (1:1.4.31-1 -> 1:1.4.32-1)
[2023-09-17T05:38:27+0200] [ALPM] upgraded suitesparse (7.1.0-2 -> 7.2.0-2)
```

```┬─  mm@desktop:  ~    08:27  17.09
╰─>$ input-remapper-gtk
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 39, in <module>
    from inputremapper.gui.reader_service import ReaderService
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/reader_service.py", line 55, in <module>
    from inputremapper.configs.input_config import InputCombination, InputConfig
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 51, in <module>
    class InputConfig(BaseModel):
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 253, in InputConfig
    @root_validator
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.3/u/root-validator-pre-skip
┬─  mm@desktop:  ~    08:27  17.09┬─  mm@desktop:  ~    08:27  17.09
╰─>$ input-remapper-gtk
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 39, in <module>
    from inputremapper.gui.reader_service import ReaderService
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/reader_service.py", line 55, in <module>
    from inputremapper.configs.input_config import InputCombination, InputConfig
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 51, in <module>
    class InputConfig(BaseModel):
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 253, in InputConfig
    @root_validator
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.3/u/root-validator-pre-skip
┬─  mm@desktop:  ~    08:27  17.09┬─  mm@desktop:  ~    08:27  17.09
╰─>$ input-remapper-gtk
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 39, in <module>
    from inputremapper.gui.reader_service import ReaderService
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/reader_service.py", line 55, in <module>
    from inputremapper.configs.input_config import InputCombination, InputConfig
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 51, in <module>
    class InputConfig(BaseModel):
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 253, in InputConfig
    @root_validator
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.3/u/root-validator-pre-skip
┬─  mm@desktop:  ~    08:27  17.09┬─  mm@desktop:  ~    08:27  17.09
╰─>$ input-remapper-gtk
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 39, in <module>
    from inputremapper.gui.reader_service import ReaderService
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/reader_service.py", line 55, in <module>
    from inputremapper.configs.input_config import InputCombination, InputConfig
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 51, in <module>
    class InputConfig(BaseModel):
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 253, in InputConfig
    @root_validator
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.3/u/root-validator-pre-skip```

**Comment by tchofy** [comment]
I'm on arch as well, downgrading just `python-pydantic` makes it work again for me, but it might cause problems if you use other packages that rely on it.

**Comment by jeandelafontaine18** [comment]
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 39, in <module>
    from inputremapper.gui.reader_service import ReaderService
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/reader_service.py", line 55, in <module>
    from inputremapper.configs.input_config import InputCombination, InputConfig
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 51, in <module>
    class InputConfig(BaseModel):
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 253, in InputConfig
    @root_validator
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.3/u/root-validator-pre-skip

**Comment by jeandelafontaine18** [comment]
> I'm on arch as well, downgrading just `python-pydantic` makes it work again for me, but it might cause problems if you use other packages that rely on it.

what version did you downgrade ? thx

**Comment by tchofy** [comment]
> > I'm on arch as well, downgrading just `python-pydantic` makes it work again for me, but it might cause problems if you use other packages that rely on it.
> 
> what version did you downgrade ? thx

`python-pydantic 1.10.9-1` specifically. The update from `1.10.9-1` to `2.3.0` was what broke input-remapper for me.

**Comment by Delta-in-hub** [comment]
Same issue on arch.

**Comment by jeandelafontaine18** [comment]
> > > I'm on arch as well, downgrading just `python-pydantic` makes it work again for me, but it might cause problems if you use other packages that rely on it.
> > 
> > 
> > what version did you downgrade ? thx
> 
> `python-pydantic 1.10.9-1` specifically. The update from `1.10.9-1` to `2.3.0` was what broke input-remapper for me.

worked for me tho, thanks man

**Comment by 7abc39bd7efb38** [comment]
Thanks for your help. I was able to get it working by doing the following:
```sudo pip install -U pydantic==1.10.9
sudo pip install --no-binary :all: git+https://github.com/sezanzeb/input-remapper.git@6054125```
I also used v1.5.1 of input-remapper. I'm sure 2.0 would work just fine, but installing one using dnf and the other via pip I didn't want to mess. I'd rather roll back to what I know worked for me. Also, for some reason I had to use the commit hash instead of the v1.5.1 tag.

**Comment by Lancaban** [comment]
I am stuck, I am having the same problem, but when trying to downgrade/install as mentioned by others above, pip gives me a warning about an externally managed environment. 

I tried manually downloading the older version and installing with Pacman -U
I tried installing through pipx

still can not start the service, and get the same error messages

**Comment by kjozsa** [comment]
@Lancaban fellow arch user here. You can try to do `sudo pip install -U pydantic==1.10.9 --break-system-packages` until the issue gets fixed in the upstream, it made input-remapper work for me again.

**Comment by Lancaban** [comment]
That did the trick!

Thank you so much!!!

**Comment by LumenYoung** [comment]
To which upstream should this problem be reported to? Is it already reported or should some of us do that? 

I manage to make it work by downgrading the pydantic but I think it should only be a temporary workaround. 

Bests

**Comment by kjozsa** [comment]
I'd assume that input-remapper's source code needs to 
a) adapt to the new pydantic
b) hardwire the old pydantic as its dependency

**Comment by LumenYoung** [comment]
> I'd assume that input-remapper's source code needs to a) adapt to the new pydantic b) hardwire the old pydantic as its dependency

It seems that input-remapper should adapt to the newer pydantic. But I assume that sezanzeb is not very active right now, his profile suggest that he is not very active on the project right now.

**Comment by Inglend** [comment]
> `sudo pip install -U pydantic==1.10.9 --break-system-packages`

is it possible to have the old pydantic installed via pip and the new one via package manager at the same time or will it conflict?

**Comment by LumenYoung** [comment]
> > `sudo pip install -U pydantic==1.10.9 --break-system-packages`
> 
> is it possible to have the old pydantic installed via pip and the new one via package manager at the same time or will it conflict?

I think it is possible if you create manually a venv for pydantic and specify that python version as the starting env for input-remapper. I don't need it right now since I don't have something rely on pydantic right now. You might have a try, I don't think it would be a problem.

**Comment by stasadev** [comment]
Everyone is welcome to try #773, it works with both pydantic v1 and v2.

**Comment by stasadev** [comment]
For Arch users, add this to [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=input-remapper-git):

```
source+=("pydantic.patch::https://github.com/sezanzeb/input-remapper/commit/1ee15f86aff83844a359227b12163db915af2eeb.patch")
prepare() {
	cd "$srcdir"/"$_gitname"
	patch -Np1 -i "$srcdir/pydantic.patch"
}
```

**Comment by SuperJugy** [comment]
If I ran the `sudo pip install -U pydantic==1.10.9 --break-system-packages` command, what do I need to do to revert to version 2?

**Comment by stasadev** [comment]
@SuperJugy run this:

```
sudo pacman -S --overwrite "*" python-pydantic
```

**Comment by pythcoiner** [comment]
i've got the same issue on arch, downgrading pydantic from cache works well for me:

```
sudo pacman -U /var/cache/pacman/pkg/python-pydantic-1.10.9-1-x86_64.pkg.tar.zst
```
