### ISSUE TITLE
Error launching the application

### ISSUE THREAD

**Issue by AccaGihu** [sezanzeb/input-remapper#781]
Iìve been using this program for a while without errors, now, after a system update, I'm getting this error:
````
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 39, in <module>
    from inputremapper.gui.reader_service import ReaderService
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/reader_service.py", line 55, in <module>
    from inputremapper.configs.input_config import InputCombination, InputConfig
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 51, in <module>
    class InputConfig(BaseModel):
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 253, in InputConfig
    @root_validator
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.3/u/root-validator-pre-skip
````
The same is if I run the app as root or normal user.
Some infos about my system:
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.5-1-MANJARO (64-bit)
Graphics Platform: X11

Since the errors reference python, my python --version returns Python 3.11.5

**Comment by AccaGihu** [comment]
I'm sorry, I found infos on manjaro forum shortly after opening the issue, I just had to rebuild the application, I did it with Pamac, everything is working, it wasn't an issue with this software.
