### ISSUE TITLE
Fails to start after recent Arch/Manjaro updates

### ISSUE THREAD

**Issue by izzylaif** [sezanzeb/input-remapper#787]
input-remapper-gtk                                                                                                                                           

```
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 39, in <module>
    from inputremapper.gui.reader_service import ReaderService
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/reader_service.py", line 55, in <module>
    from inputremapper.configs.input_config import InputCombination, InputConfig
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 51, in <module>
    class InputConfig(BaseModel):
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 253, in InputConfig
    @root_validator
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.3/u/root-validator-pre-skip
```

**Comment by sezanzeb** [comment]
`input-remapper-control --version`?

**Comment by sezanzeb** [comment]
Yeah, this has luckily already been fixed: https://github.com/sezanzeb/input-remapper/issues/769
