### ISSUE TITLE
not loading on mx

### ISSUE THREAD

**Issue by johnclark-ops** [sezanzeb/input-remapper#921]
im running mx linux 
it installed fine but its not asking me for permision
so i entered the command and here is the output

Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 32, in <module>
    gi.require_version('GtkSource', '4')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available

when i run the comand to run the app in terminal it gives this output

Traceback (most recent call last):
File "/usr/bin/input-remapper-gtk", line 32, in
gi.require_version('GtkSource', '4')
File "/usr/lib/python3/dist-packages/gi/init.py", line 126, in require_version
raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available

i did get this to work on ubuntu gnome but not mx :(

please help, thanks

**Comment by johnclark-ops** [comment]
when i run the comand in terminal it gives this output

Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 32, in <module>
    gi.require_version('GtkSource', '4')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available

i did get this to work on ubuntu gnome but not mx :(

**Comment by johnclark-ops** [comment]
so i tried this comand


sudo apt install git

output

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.39.2-1.1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 google-chrome-stable : Depends: libu2f-udev but it is not installable
 input-remapper : Depends: libpython3-dev but it is not installable
                  Depends: libdbus-1-dev but it is not installable
                  Depends: python3-setuptools but it is not installable
                  Depends: python3-evdev but it is not installable
                  Depends: python3-pydbus but it is not installable
                  Depends: gettext but it is not installable
                  Depends: libgtksourceview-4-dev but it is not installable
                  Depends: python3-pydantic but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by johnclark-ops** [comment]
it now works after i installed blender(i think that had the pacages needed(gtk 4)

**Comment by johnclark-ops** [comment]
and some other apps
