### ISSUE TITLE
Cannot start input-remapper-gtk - ModuleNotFoundError: No module named 'inputremapper.logger'

### ISSUE THREAD

**Issue by broccoliiiiiii** [sezanzeb/input-remapper#976]
I installed Input Mapper earlier and it was working without issue until I restarted my system and now it won't launch. Uninstalling/purging and reinstalling yields no change. Terminal output is as follows.

> Traceback (most recent call last):
>   File "/usr/bin/input-remapper-gtk", line 41, in <module>
>     from inputremapper.logger import logger, update_verbosity, log_info
> ModuleNotFoundError: No module named 'inputremapper.logger'
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 228, in partial_apport_excepthook
>     return apport_excepthook(binary, exc_type, exc_obj, exc_tb)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 144, in apport_excepthook
>     os.open(pr_filename, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), "wb"
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> PermissionError: [Errno 13] Permission denied: '/var/crash/_usr_bin_input-remapper-gtk.1000.crash'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/bin/input-remapper-gtk", line 41, in <module>
>     from inputremapper.logger import logger, update_verbosity, log_info
> ModuleNotFoundError: No module named 'inputremapper.logger'

Running input-remapper-gtk with sudo just yields the original exception above without the permissions error.

> Traceback (most recent call last):
>   File "/usr/bin/input-remapper-gtk", line 41, in <module>
>     from inputremapper.logger import logger, update_verbosity, log_info
> ModuleNotFoundError: No module named 'inputremapper.logger'

OS is Linux Mint 22 Cinammon. Currently installed via the Software Manager. Other methods of installation have yielded the same result.

**Comment by broccoliiiiiii** [comment]
To add to this, the system is attempting to start the Input Remapper service on boot-up, which it is unable to do, which is causing the boot-up process to take way longer than it usually does and causes the CPU temperature to spike. The error given by systemd is as follows.

>  1:00:49 PM systemd: Failed to start input-remapper-daemon.service - Service to inject keycodes without the GUI application.

I'm going to disable the service for now.

**Comment by sezanzeb** [comment]
> I installed Input Mapper earlier

how did you install it? Try to reinstall it

**Comment by sezanzeb** [comment]
> OS is Linux Mint 22 Cinammon. Currently installed via the Software Manager. Other methods of installation have yielded the same result.

oh sorry, overlooked that one

**Comment by sezanzeb** [comment]
there were recent changes to the input-remapper source code on git that could cause `ModuleNotFoundError: No module named 'inputremapper.logger'`.

However, that would imply that somehow your system has pulled the newest input-remappe source code without installing it properly, for whatever reason.

What is the output of

```
find /usr/local/lib/python3.*/dist-packages/inputremapper
```

?

**Comment by broccoliiiiiii** [comment]
> there were recent changes to the input-remapper source code on git that could cause `ModuleNotFoundError: No module named 'inputremapper.logger'`.
> 
> However, that would imply that somehow your system has pulled the newest input-remapper source code without installing it properly, for whatever reason.
> 
> What is the output of
> 
> ```
> find /usr/local/lib/python3.*/dist-packages/inputremapper
> ```
> 
> ?

Text wall incoming.

```/usr/local/lib/python3.12/dist-packages/inputremapper
/usr/local/lib/python3.12/dist-packages/inputremapper/__pycache__
/usr/local/lib/python3.12/dist-packages/inputremapper/__pycache__/exceptions.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/__pycache__/input_event.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/__pycache__/utils.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/__pycache__/daemon.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/__pycache__/commit_hash.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/__pycache__/__init__.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/__pycache__/user.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/__pycache__/groups.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/ipc
/usr/local/lib/python3.12/dist-packages/inputremapper/ipc/__pycache__
/usr/local/lib/python3.12/dist-packages/inputremapper/ipc/__pycache__/socket.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/ipc/__pycache__/__init__.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/ipc/__pycache__/shared_dict.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/ipc/__pycache__/pipe.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/ipc/socket.py
/usr/local/lib/python3.12/dist-packages/inputremapper/ipc/pipe.py
/usr/local/lib/python3.12/dist-packages/inputremapper/ipc/__init__.py
/usr/local/lib/python3.12/dist-packages/inputremapper/ipc/shared_dict.py
/usr/local/lib/python3.12/dist-packages/inputremapper/commit_hash.py
/usr/local/lib/python3.12/dist-packages/inputremapper/groups.py
/usr/local/lib/python3.12/dist-packages/inputremapper/logging
/usr/local/lib/python3.12/dist-packages/inputremapper/logging/__pycache__
/usr/local/lib/python3.12/dist-packages/inputremapper/logging/__pycache__/logger.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/logging/__pycache__/__init__.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/logging/__pycache__/formatter.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/logging/formatter.py
/usr/local/lib/python3.12/dist-packages/inputremapper/logging/__init__.py
/usr/local/lib/python3.12/dist-packages/inputremapper/logging/logger.py
/usr/local/lib/python3.12/dist-packages/inputremapper/daemon.py
/usr/local/lib/python3.12/dist-packages/inputremapper/configs
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__pycache__
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__pycache__/base_config.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__pycache__/data.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__pycache__/paths.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__pycache__/__init__.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__pycache__/input_config.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__pycache__/validation_errors.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__pycache__/system_mapping.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__pycache__/mapping.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__pycache__/migrations.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__pycache__/preset.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__pycache__/global_config.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/base_config.py
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/mapping.py
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/paths.py
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/preset.py
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/validation_errors.py
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/input_config.py
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/migrations.py
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/__init__.py
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/system_mapping.py
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/data.py
/usr/local/lib/python3.12/dist-packages/inputremapper/configs/global_config.py
/usr/local/lib/python3.12/dist-packages/inputremapper/input_event.py
/usr/local/lib/python3.12/dist-packages/inputremapper/utils.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/__pycache__
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/__pycache__/gettext.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/__pycache__/utils.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/__pycache__/reader_service.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/__pycache__/autocompletion.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/__pycache__/__init__.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/__pycache__/controller.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/__pycache__/reader_client.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/__pycache__/data_manager.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/__pycache__/user_interface.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/reader_service.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/messages
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/messages/__pycache__
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/messages/__pycache__/message_broker.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/messages/__pycache__/message_types.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/messages/__pycache__/__init__.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/messages/__pycache__/message_data.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/messages/message_broker.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/messages/__init__.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/messages/message_data.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/messages/message_types.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/reader_client.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/autocompletion.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/data_manager.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/gettext.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/utils.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/__init__.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/controller.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/__pycache__
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/__pycache__/editor.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/__pycache__/presets.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/__pycache__/__init__.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/__pycache__/device_groups.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/__pycache__/common.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/__pycache__/main.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/presets.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/main.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/common.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/device_groups.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/editor.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/components/__init__.py
/usr/local/lib/python3.12/dist-packages/inputremapper/gui/user_interface.py
/usr/local/lib/python3.12/dist-packages/inputremapper/__init__.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/__pycache__
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/__pycache__/global_uinputs.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/__pycache__/numlock.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/__pycache__/injector.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/__pycache__/__init__.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/__pycache__/event_reader.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/__pycache__/context.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/injector.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/event_reader.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/macros
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/macros/__pycache__
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/macros/__pycache__/macro.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/macros/__pycache__/parse.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/macros/__pycache__/__init__.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/macros/macro.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/macros/parse.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/macros/__init__.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/numlock.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/global_uinputs.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/context.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/__init__.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/null_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/rel_to_abs_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/macro_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/mapping_parser.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/rel_to_rel_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/abs_to_abs_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/axis_switch_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/rel_to_btn_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/mapping_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/abs_to_rel_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/__init__.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/abs_to_btn_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/key_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/combination_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/hierarchy_handler.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__pycache__/axis_transform.cpython-312.pyc
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/rel_to_rel_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/mapping_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/hierarchy_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/axis_switch_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/rel_to_btn_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/macro_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/rel_to_abs_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/key_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/axis_transform.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/abs_to_abs_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/abs_to_btn_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/null_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/mapping_parser.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/__init__.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/abs_to_rel_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/injection/mapping_handlers/combination_handler.py
/usr/local/lib/python3.12/dist-packages/inputremapper/exceptions.py
/usr/local/lib/python3.12/dist-packages/inputremapper/user.py```

**Comment by sezanzeb** [comment]
fascinating.

```
cat /usr/local/lib/python3.12/dist-packages/inputremapper/commit_hash.py
```

please

**Comment by sezanzeb** [comment]
and

```
find /usr -iname "*inputremapper"
```

**Comment by broccoliiiiiii** [comment]
> Thanks. now
> 
> ```
> find /usr -iname "*inputremapper"
> ```
> 
> please

```
/usr/lib/python3/dist-packages/inputremapper
/usr/share/doc/python3-inputremapper
/usr/local/lib/python3.12/dist-packages/inputremapper
```

**Comment by sezanzeb** [comment]
you have two input-remapper installations in your system. One in /usr/lib, and one in /usr/local/lib.

Try to uninstall input-remapper completely, via `apt remove input-remapper` and `pip uninstall input-remapper --break-system-packages`, then check if these folders in /usr are still there, and if so, remove them via `sudo rm`

Then install input-remapper from scratch.

**Comment by broccoliiiiiii** [comment]
This fixed it, working fine now. Thanks!
