### ISSUE TITLE
 input-remapper-gtk results in DeprecationWarning, unsupported operand type(s)

### ISSUE THREAD

**Issue by duskallegro** [sezanzeb/input-remapper#983]
When running input-remapper-gtk I get:

```
python-evdev 1.6.1
/usr/bin/input-remapper-control:313: DeprecationWarning: in 3.12 __contains__ will no longer raise TypeError, but will return True or
False depending on whether the value is a member or the value of a member
  if options.command in Internals:
Traceback (most recent call last):
  File "/usr/bin/input-remapper-control", line 414, in <module>
    main(options)
  File "/usr/bin/input-remapper-control", line 313, in main
    if options.command in Internals:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 745, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'str' and 'EnumType'
ERROR: Failed to pkexec the reader-service, code 256
```
Anyone had this issue? I'm on Debian Bookworm.

**Comment by sezanzeb** [comment]
already fixed in https://github.com/sezanzeb/input-remapper/commit/5f3d98162a2f9a94b8dd0ab40fddfff71a706e15

try to reinstall
